# -*- coding: utf-8 -*-
"""The ten RepairFlow collaboration diagrams (content + grid layout)."""
from bpmngen import Diagram

SERVICE, TECH, LEITUNG, DISPO = "Service / Annahme", "Techniker", "Werkstattleitung", "Ersatzteil-Disposition"
KUNDE, LIEF = "Kunde", "Lieferant"

DIAGRAMS = []


def build_01():
    d = Diagram("01", "KI-Sofortdiagnose und Voranmeldung", [SERVICE, DISPO, LEITUNG], pools_top=[KUNDE],
                doc="Der Kunde laedt in der RepairFlow-App Foto, Video oder Tonaufnahme des defekten Geraets hoch. "
                    "RepairFlow erstellt automatisch Diagnosevorschlag, Vorab-Kostenvoranschlag, prueft die Teileverfuegbarkeit "
                    "ueber alle Filialen und schlaegt Filiale und Termin vor. Bestaetigt der Kunde, entsteht eine Voranmeldung "
                    "mit vorreservierten Ersatzteilen.")
    n, f = d.node, d.flow
    n("Start_01", "start", "Anfrage eingegangen", 0, 0, trigger="message", msg="Sofortdiagnose-Anfrage")
    n("Merge_01", "xor", "", 0, 1)
    n("T01_Medien", "service", "Medienanhang prüfen und speichern", 0, 2)
    n("GW01_Auswertbar", "xor", "Medien auswertbar?", 0, 3)
    n("T01_Rueckfrage", "send", "Bessere Aufnahme anfordern", 0, 4, 1)
    n("T01_NeueAufnahme", "receive", "Neue Aufnahme empfangen", 0, 5, 1, msg="Neue Aufnahme")
    n("T01_KI", "businessRule", "KI-Diagnosevorschlag erstellen", 0, 6, type="repairflow.ki-diagnose")
    n("T01_VorabKVA", "service", "Vorab-Kostenvoranschlag berechnen", 0, 7)
    n("T01_Verfuegbarkeit", "service", "Verfügbarkeit in allen Filialen prüfen", 1, 8)
    n("T01_Termin", "service", "Filiale und Terminvorschlag ermitteln", 2, 8)
    n("T01_Senden", "send", "Sofortdiagnose an Kunde senden", 0, 9)
    n("GW01_Warten", "event", "", 0, 10)
    n("E01_Bestaetigt", "catch", "Voranmeldung bestätigt", 0, 11, trigger="message", msg="Voranmeldung bestätigen")
    n("E01_Timer", "catch", "7 Tage keine Reaktion", 0, 11, 1, trigger="timer", duration="P7D")
    n("T01_Archiv", "service", "Anfrage archivieren", 0, 12, 1)
    n("T01_Voranmeldung", "service", "Voranmeldung anlegen", 0, 12)
    n("T01_Reservieren", "service", "Ersatzteile vorreservieren", 1, 13)
    n("T01_Bestaetigung", "send", "Bestätigung an Kunde senden", 0, 14)
    n("Join_01", "xor", "", 0, 15)
    n("End_01", "end", "Sofortdiagnose abgeschlossen", 0, 16)
    f("Start_01", "Merge_01"); f("Merge_01", "T01_Medien"); f("T01_Medien", "GW01_Auswertbar")
    f("GW01_Auswertbar", "T01_KI", "ja", "=medienAuswertbar")
    f("GW01_Auswertbar", "T01_Rueckfrage", "nein", "=not(medienAuswertbar)")
    f("T01_Rueckfrage", "T01_NeueAufnahme"); f("T01_NeueAufnahme", "Merge_01", loop=1)
    f("T01_KI", "T01_VorabKVA"); f("T01_VorabKVA", "T01_Verfuegbarkeit"); f("T01_Verfuegbarkeit", "T01_Termin")
    f("T01_Termin", "T01_Senden"); f("T01_Senden", "GW01_Warten")
    f("GW01_Warten", "E01_Bestaetigt"); f("GW01_Warten", "E01_Timer")
    f("E01_Timer", "T01_Archiv"); f("T01_Archiv", "Join_01")
    f("E01_Bestaetigt", "T01_Voranmeldung"); f("T01_Voranmeldung", "T01_Reservieren")
    f("T01_Reservieren", "T01_Bestaetigung"); f("T01_Bestaetigung", "Join_01"); f("Join_01", "End_01")
    d.msg(KUNDE, "Start_01", "Foto / Video / Ton + Symptome")
    d.msg("T01_Rueckfrage", KUNDE, "Rückfrage")
    d.msg(KUNDE, "T01_NeueAufnahme", "Neue Aufnahme")
    d.msg("T01_Senden", KUNDE, "Diagnose, Vorab-KVA, Termin")
    d.msg(KUNDE, "E01_Bestaetigt", "Bestätigung")
    d.msg("T01_Bestaetigung", KUNDE, "Bestätigung der Voranmeldung")
    d.data("T01_Medien", "Medienanhang")
    d.data("T01_KI", "KI-Diagnose-vorschlag")
    d.data("T01_VorabKVA", "Kosten-voranschlag [vorläufig]")
    d.data("T01_Voranmeldung", "Voranmeldung")
    d.data("T01_Reservieren", "Ersatzteil-Reservierung")
    d.store("T01_Verfuegbarkeit", dir="in")
    return d


def build_02():
    d = Diagram("02", "Auftragsannahme, Geräteregistrierung und Terminplanung", [SERVICE, LEITUNG], pools_top=[KUNDE],
                doc="Der Kunde bringt das Geraet in die Filiale. Daten aus einer Voranmeldung werden uebernommen, das Geraet "
                    "registriert, der Reparaturauftrag angelegt und von der Werkstattleitung eingeplant (Kapazitaet, Techniker, Termin).")
    n, f = d.node, d.flow
    n("Start_02", "start", "Kunde erschienen", 0, 0, trigger="message", msg="Gerät abgegeben")
    n("GW02_Voranmeldung", "xor", "Voranmeldung vorhanden?", 0, 1)
    n("T02_Uebernehmen", "service", "Voranmeldungsdaten übernehmen", 0, 2)
    n("T02_Kundendaten", "user", "Kundendaten erfassen", 0, 2, 1)
    n("Join_02a", "xor", "", 0, 3)
    n("T02_Geraet", "user", "Gerät registrieren", 0, 4)
    n("T02_Symptome", "user", "Symptome und Zubehör dokumentieren", 0, 5)
    n("T02_Sicht", "manual", "Sichtprüfung durchführen", 0, 6)
    n("T02_Auftrag", "service", "Reparaturauftrag anlegen", 0, 7)
    n("T02_Auslastung", "service", "Werkstattauslastung prüfen", 1, 8)
    n("GW02_Kapazitaet", "xor", "Kapazität in Filiale frei?", 1, 9)
    n("T02_Umleiten", "user", "Auftrag an andere Filiale umleiten", 1, 10, 1)
    n("T02_Techniker", "user", "Techniker zuweisen", 1, 10)
    n("T02_Termin", "user", "Werkstatttermin festlegen", 1, 11)
    n("Join_02b", "xor", "", 1, 12)
    n("T02_Beleg", "send", "Annahmebeleg und Termin an Kunde senden", 0, 13)
    n("T02_Einlagern", "manual", "Gerät kennzeichnen und einlagern", 0, 14)
    n("End_02", "end", "Auftrag angenommen", 0, 15)
    f("Start_02", "GW02_Voranmeldung")
    f("GW02_Voranmeldung", "T02_Uebernehmen", "ja", "=voranmeldungVorhanden")
    f("GW02_Voranmeldung", "T02_Kundendaten", "nein", "=not(voranmeldungVorhanden)")
    f("T02_Uebernehmen", "Join_02a"); f("T02_Kundendaten", "Join_02a")
    f("Join_02a", "T02_Geraet"); f("T02_Geraet", "T02_Symptome"); f("T02_Symptome", "T02_Sicht")
    f("T02_Sicht", "T02_Auftrag"); f("T02_Auftrag", "T02_Auslastung"); f("T02_Auslastung", "GW02_Kapazitaet")
    f("GW02_Kapazitaet", "T02_Techniker", "ja", "=kapazitaetFrei")
    f("GW02_Kapazitaet", "T02_Umleiten", "nein", "=not(kapazitaetFrei)")
    f("T02_Techniker", "T02_Termin"); f("T02_Termin", "Join_02b"); f("T02_Umleiten", "Join_02b")
    f("Join_02b", "T02_Beleg"); f("T02_Beleg", "T02_Einlagern"); f("T02_Einlagern", "End_02")
    d.msg(KUNDE, "Start_02", "Gerät + Auftragswunsch")
    d.msg("T02_Beleg", KUNDE, "Annahmebeleg, Termin")
    d.data("T02_Uebernehmen", "Voranmeldung", dir="in")
    d.data("T02_Geraet", "Gerät")
    d.data("T02_Auftrag", "Reparatur-auftrag [angenommen]")
    d.data("T02_Termin", "Reparatur-auftrag [eingeplant]")
    d.store("T02_Auftrag")
    d.store("T02_Auslastung", name="Technikerplan", dir="in")
    d.store("T02_Termin", name="Technikerplan")
    return d


def build_03():
    d = Diagram("03", "Fehlerdiagnose", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Der Techniker prueft den KI-Diagnosevorschlag, fuehrt Funktionstest und Messung durch, dokumentiert den "
                    "Fehlerbefund und legt den Ersatzteilbedarf fest. RepairFlow bewertet die Wirtschaftlichkeit der Reparatur.")
    n, f = d.node, d.flow
    n("Start_03", "start", "Auftrag eingeplant", 1, 0)
    n("T03_Status", "service", "Auftragsstatus auf 'in Diagnose' setzen", 1, 1)
    n("T03_KI", "user", "KI-Diagnosevorschlag sichten", 1, 2)
    n("Merge_03", "xor", "", 1, 3)
    n("T03_Test", "user", "Funktionstest durchführen und Messwerte erfassen", 1, 4)
    n("GW03_Repro", "xor", "Fehler reproduzierbar?", 1, 5)
    n("T03_Erweitert", "manual", "Erweiterte Prüfung durchführen", 1, 6, 1)
    n("T03_Befund", "user", "Fehlerbefund dokumentieren", 1, 6)
    n("T03_Teile", "user", "Ersatzteilbedarf festlegen", 1, 7)
    n("T03_Wirtschaft", "businessRule", "Wirtschaftlichkeit der Reparatur prüfen", 1, 8, type="repairflow.wirtschaftlichkeit")
    n("GW03_Wirtschaft", "xor", "Reparatur wirtschaftlich?", 1, 9, label="left")
    n("T03_Totalschaden", "send", "Kunde über Totalschaden informieren", 0, 10)
    n("T03_Schliessen", "service", "Auftrag als nicht reparierbar schließen", 0, 11)
    n("T03_Aufwand", "user", "Reparaturaufwand schätzen", 1, 10)
    n("T03_Abschluss", "service", "Diagnose abschließen und KVA anstoßen", 1, 11)
    n("Join_03", "xor", "", 1, 12)
    n("End_03", "end", "Diagnose abgeschlossen", 1, 13)
    f("Start_03", "T03_Status"); f("T03_Status", "T03_KI"); f("T03_KI", "Merge_03"); f("Merge_03", "T03_Test")
    f("T03_Test", "GW03_Repro")
    f("GW03_Repro", "T03_Befund", "ja", "=fehlerReproduzierbar")
    f("GW03_Repro", "T03_Erweitert", "nein", "=not(fehlerReproduzierbar)")
    f("T03_Erweitert", "Merge_03", loop=1)
    f("T03_Befund", "T03_Teile"); f("T03_Teile", "T03_Wirtschaft"); f("T03_Wirtschaft", "GW03_Wirtschaft")
    f("GW03_Wirtschaft", "T03_Aufwand", "ja", "=reparaturWirtschaftlich")
    f("GW03_Wirtschaft", "T03_Totalschaden", "nein", "=not(reparaturWirtschaftlich)")
    f("T03_Totalschaden", "T03_Schliessen"); f("T03_Schliessen", "Join_03")
    f("T03_Aufwand", "T03_Abschluss"); f("T03_Abschluss", "Join_03"); f("Join_03", "End_03")
    d.msg("T03_Totalschaden", KUNDE, "Info Totalschaden")
    d.data("T03_Status", "Reparatur-auftrag [in Diagnose]")
    d.data("T03_KI", "KI-Diagnose-vorschlag", dir="in")
    d.data("T03_Befund", "Fehlerbefund")
    d.store("T03_Status")
    return d


def build_04():
    d = Diagram("04", "Kostenvoranschlag und Kundenfreigabe", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Aus dem Fehlerbefund entsteht der Kostenvoranschlag. RepairFlow sendet ihn an den Kunden und wartet auf "
                    "Freigabe oder Ablehnung; bleibt die Reaktion aus, wird der KVA mit Erinnerung erneut gesendet.")
    n, f = d.node, d.flow
    n("Start_04", "start", "Diagnose abgeschlossen", 1, 0)
    n("T04_Positionen", "user", "KVA-Positionen erfassen", 1, 1)
    n("T04_Preise", "service", "Ersatzteilpreise übernehmen", 1, 2)
    n("T04_Berechnen", "service", "Kostenvoranschlag berechnen", 1, 3)
    n("T04_Pruefen", "user", "Kostenvoranschlag prüfen", 0, 4)
    n("T04_Status", "service", "Auftragsstatus auf 'KVA offen' setzen", 0, 5)
    n("Merge_04", "xor", "", 0, 6)
    n("T04_Senden", "send", "Kostenvoranschlag an Kunde senden", 0, 7)
    n("GW04_Warten", "event", "", 0, 8)
    n("E04_Freigabe", "catch", "Freigabe erhalten", 0, 9, trigger="message", msg="KVA-Freigabe")
    n("E04_Ablehnung", "catch", "Ablehnung erhalten", 0, 11, 1, trigger="message", msg="KVA-Ablehnung")
    n("E04_Timer", "catch", "3 Tage keine Reaktion", 0, 8, 2, trigger="timer", duration="P3D")
    n("T04_Erinnerung", "service", "Erinnerung protokollieren", 0, 6, 2)
    n("T04_Freigegeben", "service", "Auftragsstatus auf 'freigegeben' setzen", 1, 9)
    n("T04_Dispo", "call", "05 Ersatzteile disponieren", 1, 10, called="Proc_05")
    n("T04_Abgelehnt", "service", "Auftragsstatus auf 'abgelehnt' setzen", 0, 12, 1)
    n("T04_Pauschale", "user", "Diagnosepauschale abrechnen", 0, 13, 1)
    n("T04_Abholung", "send", "Abholaufforderung an Kunde senden", 0, 14, 1)
    n("Join_04", "xor", "", 1, 15)
    n("End_04", "end", "KVA-Entscheidung verarbeitet", 1, 16)
    f("Start_04", "T04_Positionen"); f("T04_Positionen", "T04_Preise"); f("T04_Preise", "T04_Berechnen")
    f("T04_Berechnen", "T04_Pruefen"); f("T04_Pruefen", "T04_Status"); f("T04_Status", "Merge_04")
    f("Merge_04", "T04_Senden"); f("T04_Senden", "GW04_Warten")
    f("GW04_Warten", "E04_Freigabe"); f("GW04_Warten", "E04_Ablehnung"); f("GW04_Warten", "E04_Timer")
    f("E04_Timer", "T04_Erinnerung"); f("T04_Erinnerung", "Merge_04")
    f("E04_Freigabe", "T04_Freigegeben"); f("T04_Freigegeben", "T04_Dispo"); f("T04_Dispo", "Join_04")
    f("E04_Ablehnung", "T04_Abgelehnt"); f("T04_Abgelehnt", "T04_Pauschale"); f("T04_Pauschale", "T04_Abholung")
    f("T04_Abholung", "Join_04"); f("Join_04", "End_04")
    d.msg("T04_Senden", KUNDE, "KVA (ggf. mit Erinnerung)")
    d.msg(KUNDE, "E04_Freigabe", "Freigabe")
    d.msg(KUNDE, "E04_Ablehnung", "Ablehnung")
    d.msg("T04_Abholung", KUNDE, "Bitte abholen")
    d.data("T04_Positionen", "KVA-Position")
    d.data("T04_Berechnen", "Kosten-voranschlag")
    d.data("T04_Freigegeben", "Reparatur-auftrag [freigegeben]", pos="bottom")
    d.store("T04_Preise", dir="in")
    return d


def build_05():
    d = Diagram("05", "Ersatzteil-Verfügbarkeit und Reservierung", [TECH, DISPO], pools_top=[KUNDE],
                doc="Nach der KVA-Freigabe prueft RepairFlow je Ersatzteil den Bestand der eigenen und der anderen Filialen, "
                    "reserviert oder fordert Umlagerungen an und markiert Fehlteile fuer die Bestellung. Unterschreitet ein "
                    "Bestand den Meldebestand, entsteht ein Nachbestellvorschlag.")
    n, f = d.node, d.flow
    n("Start_05", "start", "KVA freigegeben", 1, 0)
    n("T05_Teileliste", "service", "Teileliste aus KVA übernehmen", 1, 1)
    n("Sub_05", "subprocess", "Verfügbarkeit je Ersatzteil prüfen", 1, 2, multi=True, collection="=ersatzteile", element="ersatzteil")
    n("S05_Start", "start", "Ersatzteil ausgewählt", 1, 2, parent="Sub_05")
    n("S05_Eigen", "service", "Bestand eigene Filiale prüfen", 1, 3, parent="Sub_05")
    n("GW05_Eigen", "xor", "Eigener Bestand ausreichend?", 1, 4, parent="Sub_05")
    n("S05_Reservieren", "service", "Teil in eigener Filiale reservieren", 1, 5, parent="Sub_05")
    n("S05_Andere", "service", "Bestand anderer Filialen prüfen", 1, 5, 1, parent="Sub_05")
    n("GW05_Andere", "xor", "In anderer Filiale verfügbar?", 1, 6, 1, parent="Sub_05")
    n("S05_Umlagerung", "user", "Umlagerung anfordern und Teil reservieren", 1, 7, 1, parent="Sub_05")
    n("S05_Fehlteil", "service", "Teil als Fehlteil markieren", 1, 7, 2, parent="Sub_05")
    n("S05_Join", "xor", "", 1, 8, parent="Sub_05")
    n("S05_End", "end", "Teil disponiert", 1, 9, parent="Sub_05")
    n("GW05_Fehlteile", "xor", "Fehlteile vorhanden?", 1, 10)
    n("T05_Bestellen", "call", "06 Ersatzteile bestellen", 1, 11, 2, called="Proc_06")
    n("T05_Bestaetigen", "service", "Reservierungen bestätigen", 1, 11)
    n("T05_Meldebestand", "businessRule", "Meldebestand prüfen", 1, 12, type="repairflow.meldebestand")
    n("GW05_Meldebestand", "xor", "Meldebestand unter-schritten?", 1, 13)
    n("T05_Nachbestellung", "service", "Nachbestellvorschlag erzeugen", 1, 14, 1)
    n("Join_05", "xor", "", 1, 15)
    n("T05_Beginn", "service", "Voraussichtlichen Reparaturbeginn ermitteln", 0, 16)
    n("T05_Info", "send", "Kunde über Reparaturbeginn informieren", 0, 17)
    n("End_05", "end", "Ersatzteile disponiert", 0, 18)
    f("Start_05", "T05_Teileliste"); f("T05_Teileliste", "Sub_05")
    f("S05_Start", "S05_Eigen"); f("S05_Eigen", "GW05_Eigen")
    f("GW05_Eigen", "S05_Reservieren", "ja", "=bestandAusreichend")
    f("GW05_Eigen", "S05_Andere", "nein", "=not(bestandAusreichend)")
    f("S05_Andere", "GW05_Andere")
    f("GW05_Andere", "S05_Umlagerung", "ja", "=andereFilialeVerfuegbar")
    f("GW05_Andere", "S05_Fehlteil", "nein", "=not(andereFilialeVerfuegbar)")
    f("S05_Reservieren", "S05_Join"); f("S05_Umlagerung", "S05_Join"); f("S05_Fehlteil", "S05_Join")
    f("S05_Join", "S05_End")
    f("Sub_05", "GW05_Fehlteile")
    f("GW05_Fehlteile", "T05_Bestaetigen", "nein", "=not(fehlteileVorhanden)")
    f("GW05_Fehlteile", "T05_Bestellen", "ja", "=fehlteileVorhanden")
    f("T05_Bestellen", "Join_05")
    f("T05_Bestaetigen", "T05_Meldebestand"); f("T05_Meldebestand", "GW05_Meldebestand")
    f("GW05_Meldebestand", "T05_Nachbestellung", "ja", "=meldebestandUnterschritten")
    f("GW05_Meldebestand", "Join_05", "nein", "=not(meldebestandUnterschritten)")
    f("T05_Nachbestellung", "Join_05")
    f("Join_05", "T05_Beginn"); f("T05_Beginn", "T05_Info"); f("T05_Info", "End_05")
    d.msg("T05_Info", KUNDE, "Termin Reparatur")
    d.data("T05_Teileliste", "Kosten-voranschlag", dir="in")
    d.data("T05_Bestaetigen", "Ersatzteil-Reservierung")
    d.data("T05_Nachbestellung", "Lieferanten-bestellung [Vorschlag]")
    d.store("T05_Teileliste", dir="in")
    return d


def build_06():
    d = Diagram("06", "Ersatzteil-Bestellung beim Lieferanten", [LEITUNG, DISPO, SERVICE], pools_top=[LIEF], pools_bottom=[KUNDE],
                doc="Fehlteile werden zu einer Lieferantenbestellung gebuendelt, bei Bedarf von der Werkstattleitung freigegeben "
                    "und an den Lieferanten gesendet. Nach Auftragsbestaetigung und Wareneingang werden die Teile dem Auftrag "
                    "zugeordnet; bei Verzoegerungen informiert RepairFlow den Kunden.")
    n, f = d.node, d.flow
    n("Start_06", "start", "Fehlteile gemeldet", 1, 0)
    n("T06_Buendeln", "service", "Fehlteile zu Bestellbedarf bündeln", 1, 1)
    n("Merge_06", "xor", "", 1, 2)
    n("T06_Lieferant", "user", "Lieferanten auswählen", 1, 3)
    n("T06_Bestellung", "service", "Bestellung beim Lieferanten anlegen", 1, 4)
    n("GW06_Grenze", "xor", "Über Freigabegrenze?", 1, 5)
    n("T06_Freigabe", "user", "Bestellung freigeben", 0, 6)
    n("Join_06a", "xor", "", 1, 7)
    n("T06_Senden", "send", "Bestellung an Lieferanten senden", 1, 8)
    n("T06_AB", "receive", "Auftragsbestätigung empfangen", 1, 9, msg="Auftragsbestätigung")
    n("GW06_Lieferbar", "xor", "Bestätigt und lieferbar?", 1, 10)
    n("T06_Alternative", "user", "Alternativen Lieferanten suchen", 1, 11, 1)
    n("T06_Termin", "service", "Liefertermin am Auftrag hinterlegen", 1, 11)
    n("GW06_Verzoegert", "xor", "Reparatur verzögert?", 1, 12)
    n("T06_KundeInfo", "send", "Kunde über Verzögerung informieren", 2, 13)
    n("Join_06b", "xor", "", 1, 14)
    n("T06_Lieferung", "receive", "Lieferung empfangen", 1, 15, msg="Lieferung")
    n("T06_Wareneingang", "user", "Wareneingang prüfen und buchen", 1, 16)
    n("GW06_Mangelfrei", "xor", "Lieferung mangelfrei?", 1, 17)
    n("T06_Retoure", "call", "10 Retoure abwickeln", 1, 18, 1, called="Proc_10")
    n("T06_Zuordnen", "service", "Teile dem Reparaturauftrag zuordnen", 1, 18)
    n("Join_06c", "xor", "", 1, 19)
    n("End_06", "end", "Ersatzteile eingegangen", 1, 20)
    f("Start_06", "T06_Buendeln"); f("T06_Buendeln", "Merge_06"); f("Merge_06", "T06_Lieferant")
    f("T06_Lieferant", "T06_Bestellung"); f("T06_Bestellung", "GW06_Grenze")
    f("GW06_Grenze", "T06_Freigabe", "ja", "=bestellwert > freigabegrenze")
    f("GW06_Grenze", "Join_06a", "nein", "=bestellwert <= freigabegrenze")
    f("T06_Freigabe", "Join_06a"); f("Join_06a", "T06_Senden"); f("T06_Senden", "T06_AB"); f("T06_AB", "GW06_Lieferbar")
    f("GW06_Lieferbar", "T06_Termin", "ja", "=bestaetigt and lieferbar")
    f("GW06_Lieferbar", "T06_Alternative", "nein", "=not(bestaetigt and lieferbar)")
    f("T06_Alternative", "Merge_06", loop=1)
    f("T06_Termin", "GW06_Verzoegert")
    f("GW06_Verzoegert", "T06_KundeInfo", "ja", "=reparaturVerzoegert")
    f("GW06_Verzoegert", "Join_06b", "nein", "=not(reparaturVerzoegert)")
    f("T06_KundeInfo", "Join_06b"); f("Join_06b", "T06_Lieferung"); f("T06_Lieferung", "T06_Wareneingang")
    f("T06_Wareneingang", "GW06_Mangelfrei")
    f("GW06_Mangelfrei", "T06_Zuordnen", "ja", "=lieferungMangelfrei")
    f("GW06_Mangelfrei", "T06_Retoure", "nein", "=not(lieferungMangelfrei)")
    f("T06_Retoure", "Join_06c"); f("T06_Zuordnen", "Join_06c"); f("Join_06c", "End_06")
    d.msg("T06_Senden", LIEF, "Bestellung")
    d.msg(LIEF, "T06_AB", "Auftrags-bestätigung, Liefertermin")
    d.msg(LIEF, "T06_Lieferung", "Lieferung + Lieferschein")
    d.msg("T06_KundeInfo", KUNDE, "Info: neuer Liefertermin")
    d.data("T06_Lieferant", "Lieferant", dir="in")
    d.data("T06_Bestellung", "Lieferanten-bestellung [offen]")
    d.data("T06_Termin", "Reparatur-auftrag [Teile bestellt]")
    d.data("T06_Wareneingang", "Lagerbestand")
    d.store("T06_Wareneingang")
    return d


def build_07():
    d = Diagram("07", "Reparaturdurchführung und Arbeitszeiterfassung", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Der Techniker entnimmt die reservierten Teile und arbeitet die Reparaturschritte mit Zeiterfassung ab. "
                    "Zusatzbefunde fuehren zu einem Nachtrags-KVA, den der Kunde freigeben muss. Nach Endkontrolle wird der "
                    "Auftrag auf 'fertig' gesetzt.")
    n, f = d.node, d.flow
    n("Start_07", "start", "Ersatzteile verfügbar", 1, 0)
    n("T07_Status", "service", "Auftragsstatus auf 'in Reparatur' setzen", 1, 1)
    n("T07_Entnahme", "user", "Reservierte Ersatzteile entnehmen", 1, 2)
    n("Merge_07", "xor", "", 1, 3)
    n("T07_Start", "user", "Reparaturschritt starten und Zeit erfassen", 1, 4)
    n("T07_Ausfuehren", "manual", "Reparaturschritt ausführen", 1, 5)
    n("T07_Doku", "user", "Schritt dokumentieren und Zeit stoppen", 1, 6)
    n("GW07_Weitere", "xor", "Weitere Schritte offen?", 1, 7)
    n("GW07_Zusatz", "xor", "Zusatzbefund festgestellt?", 1, 8)
    n("T07_Nachtrag", "user", "Nachtrags-KVA erstellen", 1, 9, 2)
    n("T07_NachtragSenden", "send", "Nachtrag an Kunde senden", 0, 10)
    n("T07_Entscheidung", "receive", "Kundenentscheidung empfangen", 0, 11, msg="Nachtragsentscheidung")
    n("GW07_Nachtrag", "xor", "Nachtrag freigegeben?", 0, 12)
    n("Join_07", "xor", "", 1, 13)
    n("T07_Endkontrolle", "user", "Endkontrolle durchführen und Prüfprotokoll erfassen", 1, 14)
    n("GW07_Qualitaet", "xor", "Qualität in Ordnung?", 1, 15)
    n("T07_Nacharbeit", "manual", "Nacharbeit durchführen", 1, 16, 1)
    n("T07_Fertig", "service", "Auftragsstatus auf 'fertig' setzen", 1, 16)
    n("End_07", "end", "Reparatur abgeschlossen", 1, 17)
    f("Start_07", "T07_Status"); f("T07_Status", "T07_Entnahme"); f("T07_Entnahme", "Merge_07")
    f("Merge_07", "T07_Start"); f("T07_Start", "T07_Ausfuehren"); f("T07_Ausfuehren", "T07_Doku")
    f("T07_Doku", "GW07_Weitere")
    f("GW07_Weitere", "Merge_07", "ja", "=weitereSchritte", loop=1)
    f("GW07_Weitere", "GW07_Zusatz", "nein", "=not(weitereSchritte)")
    f("GW07_Zusatz", "Join_07", "nein", "=not(zusatzbefund)")
    f("GW07_Zusatz", "T07_Nachtrag", "ja", "=zusatzbefund")
    f("T07_Nachtrag", "T07_NachtragSenden"); f("T07_NachtragSenden", "T07_Entscheidung")
    f("T07_Entscheidung", "GW07_Nachtrag")
    f("GW07_Nachtrag", "Merge_07", "ja", "=nachtragFreigegeben", loop=3)
    f("GW07_Nachtrag", "Join_07", "nein", "=not(nachtragFreigegeben)", via="right")
    f("Join_07", "T07_Endkontrolle"); f("T07_Endkontrolle", "GW07_Qualitaet")
    f("GW07_Qualitaet", "T07_Fertig", "ja", "=qualitaetOk")
    f("GW07_Qualitaet", "T07_Nacharbeit", "nein", "=not(qualitaetOk)")
    f("T07_Nacharbeit", "Join_07", loop=1)
    f("T07_Fertig", "End_07")
    d.msg("T07_NachtragSenden", KUNDE, "Nachtrags-KVA")
    d.msg(KUNDE, "T07_Entscheidung", "Freigabe / Ablehnung")
    d.data("T07_Status", "Reparatur-auftrag [in Reparatur]")
    d.data("T07_Entnahme", "Ersatzteil-Reservierung [entnommen]")
    d.data("T07_Doku", "Arbeitszeit-buchung")
    d.data("T07_Fertig", "Reparatur-auftrag [fertig]")
    d.store("T07_Status")
    return d


def build_08():
    d = Diagram("08", "Abholung, Rechnung und Zahlung", [SERVICE, TECH], pools_top=[KUNDE],
                doc="RepairFlow erstellt die Rechnung aus KVA und Arbeitszeiten und benachrichtigt den Kunden. Bei der Abholung "
                    "werden Geraet und Rechnung uebergeben, die Zahlung erfasst und der Auftrag geschlossen.")
    n, f = d.node, d.flow
    n("Start_08", "start", "Reparatur abgeschlossen", 0, 0)
    n("T08_Rechnung", "service", "Rechnung aus KVA und Arbeitszeiten erstellen", 0, 1)
    n("Merge_08", "xor", "", 0, 2)
    n("T08_Benachrichtigung", "send", "Abhol-Benachrichtigung an Kunde senden", 0, 3)
    n("GW08_Warten", "event", "", 0, 4)
    n("E08_Timer", "catch", "14 Tage nicht abgeholt", 0, 4, 1, trigger="timer", duration="P14D")
    n("T08_Erinnerung", "service", "Erinnerung protokollieren", 0, 2, 1)
    n("E08_Kunde", "catch", "Kunde zur Abholung erschienen", 0, 5, trigger="message", msg="Kunde erschienen")
    n("T08_Holen", "manual", "Gerät aus dem Lager holen", 1, 6)
    n("T08_Uebergabe", "manual", "Reparatur erläutern und Gerät übergeben", 1, 7)
    n("T08_Zahlungsart", "user", "Zahlungsart erfassen", 0, 8)
    n("GW08_Zahlungsart", "xor", "Zahlungsart?", 0, 9)
    n("T08_Kassieren", "user", "Zahlung kassieren", 0, 10)
    n("T08_Versand", "send", "Rechnung mit Zahlungsziel versenden", 0, 11, 1)
    n("Join_08", "xor", "", 0, 12)
    n("T08_Verbuchen", "service", "Zahlung verbuchen", 0, 13)
    n("T08_Schliessen", "service", "Auftrag auf 'abgeholt' setzen und schließen", 0, 14)
    n("T08_Bestaende", "service", "Reservierungen und Bestände abschließen", 0, 15)
    n("T08_Bewertung", "send", "Bewertungsanfrage an Kunde senden", 0, 16)
    n("End_08", "end", "Auftrag abgeschlossen", 0, 17)
    f("Start_08", "T08_Rechnung"); f("T08_Rechnung", "Merge_08"); f("Merge_08", "T08_Benachrichtigung")
    f("T08_Benachrichtigung", "GW08_Warten"); f("GW08_Warten", "E08_Kunde"); f("GW08_Warten", "E08_Timer")
    f("E08_Timer", "T08_Erinnerung"); f("T08_Erinnerung", "Merge_08")
    f("E08_Kunde", "T08_Holen"); f("T08_Holen", "T08_Uebergabe"); f("T08_Uebergabe", "T08_Zahlungsart")
    f("T08_Zahlungsart", "GW08_Zahlungsart")
    f("GW08_Zahlungsart", "T08_Kassieren", "bar / Karte", '=zahlungsart in ["bar", "karte"]')
    f("GW08_Zahlungsart", "T08_Versand", "auf Rechnung", '=zahlungsart = "rechnung"')
    f("T08_Kassieren", "Join_08"); f("T08_Versand", "Join_08"); f("Join_08", "T08_Verbuchen")
    f("T08_Verbuchen", "T08_Schliessen"); f("T08_Schliessen", "T08_Bestaende"); f("T08_Bestaende", "T08_Bewertung")
    f("T08_Bewertung", "End_08")
    d.msg("T08_Benachrichtigung", KUNDE, "Abhol-Benachrichtigung (ggf. Erinnerung)")
    d.msg(KUNDE, "E08_Kunde", "Abholung")
    d.msg("T08_Versand", KUNDE, "Rechnung")
    d.msg("T08_Bewertung", KUNDE, "Bitte um Bewertung")
    d.data("T08_Rechnung", "Rechnung [offen]")
    d.data("T08_Verbuchen", "Rechnung [bezahlt]")
    d.data("T08_Schliessen", "Reparatur-auftrag [abgeholt]")
    d.store("T08_Verbuchen", name="Buchhaltung (DATEV-Export)")
    d.store("T08_Schliessen")
    return d


def build_09():
    d = Diagram("09", "Reklamation und Gewährleistung", [TECH, SERVICE, LEITUNG], pools_top=[KUNDE],
                doc="Meldet der Kunde nach der Abholung einen Mangel, wird die Reklamation dem Ursprungsauftrag zugeordnet, "
                    "der Mangel geprueft und der Gewaehrleistungsfall bewertet. Je nach Ergebnis folgt kostenfreie Nacharbeit "
                    "oder ein kostenpflichtiges Angebot.")
    n, f = d.node, d.flow
    n("Start_09", "start", "Mangel gemeldet", 1, 0, trigger="message", msg="Reklamation")
    n("T09_Erfassen", "user", "Reklamation erfassen", 1, 1)
    n("T09_Zuordnen", "service", "Ursprungsauftrag und Rechnung zuordnen", 1, 2)
    n("T09_Annehmen", "user", "Gerät annehmen und Mangel dokumentieren", 1, 3)
    n("T09_Pruefen", "manual", "Mangel prüfen", 0, 4)
    n("T09_Bewerten", "businessRule", "Gewährleistungsfall bewerten", 0, 5, type="repairflow.gewaehrleistung")
    n("GW09_Gewaehr", "xor", "Gewährleistung?", 0, 6, label="left")
    n("T09_Freigeben", "user", "Kostenfreie Nacharbeit freigeben", 2, 7)
    n("T09_Angebot", "send", "Kostenpflichtiges Angebot senden", 1, 7)
    n("T09_Entscheidung", "receive", "Kundenentscheidung empfangen", 1, 8, msg="Angebotsentscheidung")
    n("GW09_Angebot", "xor", "Angebot angenommen?", 1, 9, label="left")
    n("T09_OhneReparatur", "service", "Reklamation ohne Reparatur schließen", 1, 11, 1)
    n("Join_09a", "xor", "", 0, 10)
    n("T09_Nacharbeit", "manual", "Nacharbeit durchführen", 0, 11)
    n("GW09_Teil", "xor", "Lieferantenteil defekt?", 0, 12)
    n("T09_Retoure", "call", "10 Lieferanten-Retoure", 0, 13, 1, called="Proc_10")
    n("Join_09b", "xor", "", 0, 14)
    n("T09_Info", "send", "Kunde über Ergebnis informieren", 1, 15)
    n("T09_Abschluss", "service", "Reklamation abschließen", 1, 16)
    n("Join_09c", "xor", "", 1, 17)
    n("End_09", "end", "Reklamation abgeschlossen", 1, 18)
    f("Start_09", "T09_Erfassen"); f("T09_Erfassen", "T09_Zuordnen"); f("T09_Zuordnen", "T09_Annehmen")
    f("T09_Annehmen", "T09_Pruefen"); f("T09_Pruefen", "T09_Bewerten"); f("T09_Bewerten", "GW09_Gewaehr")
    f("GW09_Gewaehr", "T09_Freigeben", "ja", "=gewaehrleistung")
    f("GW09_Gewaehr", "T09_Angebot", "nein", "=not(gewaehrleistung)", via="right")
    f("T09_Angebot", "T09_Entscheidung"); f("T09_Entscheidung", "GW09_Angebot")
    f("GW09_Angebot", "Join_09a", "ja", "=angebotAngenommen")
    f("GW09_Angebot", "T09_OhneReparatur", "nein", "=not(angebotAngenommen)", via="right")
    f("T09_Freigeben", "Join_09a"); f("Join_09a", "T09_Nacharbeit"); f("T09_Nacharbeit", "GW09_Teil")
    f("GW09_Teil", "T09_Retoure", "ja", "=lieferantenteilDefekt")
    f("GW09_Teil", "Join_09b", "nein", "=not(lieferantenteilDefekt)")
    f("T09_Retoure", "Join_09b"); f("Join_09b", "T09_Info"); f("T09_Info", "T09_Abschluss")
    f("T09_Abschluss", "Join_09c"); f("T09_OhneReparatur", "Join_09c"); f("Join_09c", "End_09")
    d.msg(KUNDE, "Start_09", "Mangelmeldung")
    d.msg("T09_Angebot", KUNDE, "Angebot")
    d.msg(KUNDE, "T09_Entscheidung", "Annahme / Ablehnung")
    d.msg("T09_Info", KUNDE, "Ergebnis")
    d.data("T09_Erfassen", "Reklamation")
    d.data("T09_Zuordnen", "Reparatur-auftrag", dir="in")
    d.data("T09_Bewerten", "Fehlerbefund", dir="in")
    d.store("T09_Abschluss")
    return d


def build_10():
    d = Diagram("10", "Ersatzteil-Retoure und Lieferanten-Reklamation", [LEITUNG, DISPO], pools_bottom=[LIEF],
                doc="Defekte oder falsche Lieferantenteile werden beim Lieferanten reklamiert. Nach RMA-Freigabe wird das Teil "
                    "zurueckgesendet, der Bestand korrigiert und je nach Rueckmeldung Ersatzlieferung oder Gutschrift verbucht.")
    n, f = d.node, d.flow
    n("Start_10", "start", "Mangelhaftes Teil festgestellt", 1, 0)
    n("T10_Grund", "user", "Retourengrund erfassen", 1, 1)
    n("T10_Ermitteln", "service", "Bestellposition und Lieferanten ermitteln", 1, 2)
    n("T10_Anmelden", "send", "Retoure beim Lieferanten anmelden", 1, 3)
    n("Merge_10", "xor", "", 1, 4)
    n("GW10_Warten", "event", "", 1, 5)
    n("E10_Timer", "catch", "5 Tage keine Antwort", 1, 6, trigger="timer", duration="P5D")
    n("E10_RMA", "catch", "RMA-Freigabe erhalten", 1, 6, 1, trigger="message", msg="RMA-Freigabe", label="above")
    n("T10_Eskalieren", "user", "Beim Lieferanten eskalieren", 0, 7)
    n("T10_Versenden", "manual", "Teil verpacken und versenden", 1, 8)
    n("T10_Bestand", "service", "Lagerbestand korrigieren", 1, 9)
    n("T10_Rueckmeldung", "receive", "Rückmeldung des Lieferanten empfangen", 1, 10, msg="Retourenrückmeldung")
    n("GW10_Art", "xor", "Ersatz oder Gutschrift?", 1, 11)
    n("T10_Ersatz", "user", "Ersatzlieferung buchen", 1, 12)
    n("T10_Gutschrift", "service", "Gutschrift verbuchen", 1, 12, 1)
    n("Join_10a", "xor", "", 1, 13)
    n("GW10_Wartet", "xor", "Reparatur wartet auf Teil?", 1, 14)
    n("T10_Fortsetzen", "call", "07 Reparatur fortsetzen", 1, 15, 1, called="Proc_07")
    n("Join_10b", "xor", "", 1, 16)
    n("T10_Abschluss", "service", "Retoure dokumentieren und abschließen", 1, 17)
    n("End_10", "end", "Retoure abgeschlossen", 1, 18)
    f("Start_10", "T10_Grund"); f("T10_Grund", "T10_Ermitteln"); f("T10_Ermitteln", "T10_Anmelden")
    f("T10_Anmelden", "Merge_10"); f("Merge_10", "GW10_Warten")
    f("GW10_Warten", "E10_Timer"); f("GW10_Warten", "E10_RMA")
    f("E10_Timer", "T10_Eskalieren"); f("T10_Eskalieren", "Merge_10", via="top")
    f("E10_RMA", "T10_Versenden"); f("T10_Versenden", "T10_Bestand"); f("T10_Bestand", "T10_Rueckmeldung")
    f("T10_Rueckmeldung", "GW10_Art")
    f("GW10_Art", "T10_Ersatz", "Ersatz", '=rueckmeldung = "ersatz"')
    f("GW10_Art", "T10_Gutschrift", "Gutschrift", '=rueckmeldung = "gutschrift"')
    f("T10_Ersatz", "Join_10a"); f("T10_Gutschrift", "Join_10a"); f("Join_10a", "GW10_Wartet")
    f("GW10_Wartet", "T10_Fortsetzen", "ja", "=reparaturWartet")
    f("GW10_Wartet", "Join_10b", "nein", "=not(reparaturWartet)")
    f("T10_Fortsetzen", "Join_10b"); f("Join_10b", "T10_Abschluss"); f("T10_Abschluss", "End_10")
    d.msg("T10_Anmelden", LIEF, "Retoure anmelden")
    d.msg(LIEF, "E10_RMA", "RMA-Nummer")
    d.msg(LIEF, "T10_Rueckmeldung", "Ersatz / Gutschrift")
    d.data("T10_Ermitteln", "Lieferanten-bestellung", dir="in")
    d.data("T10_Bestand", "Lagerbestand")
    d.store("T10_Abschluss")
    return d


DIAGRAMS = [build_01(), build_02(), build_03(), build_04(), build_05(), build_06(), build_07(), build_08(), build_09(), build_10()]

SLUGS = {"01": "Sofortdiagnose", "02": "Auftragsannahme", "03": "Fehlerdiagnose", "04": "Kostenvoranschlag",
         "05": "Ersatzteilreservierung", "06": "Ersatzteilbestellung", "07": "Reparaturdurchfuehrung",
         "08": "Abholung", "09": "Reklamation", "10": "Retoure"}

if __name__ == "__main__":
    import os, sys
    out = sys.argv[1] if len(sys.argv) > 1 else "out"
    os.makedirs(out, exist_ok=True)
    total = 0
    for d in DIAGRAMS:
        xml = d.to_xml()
        fn = os.path.join(out, "p%s-%s.bpmn" % (d.num, SLUGS[d.num].lower()))
        with open(fn, "w", encoding="utf-8") as fh:
            fh.write(xml)
        c = d.activity_count()
        total += c
        print("%s  activities=%2d  pool=%dx%d  %s" % (fn, c, d.pool_w, d.pool_h, d.name))
    print("average activities: %.1f" % (total / len(DIAGRAMS)))
