# -*- coding: utf-8 -*-
"""The ten RepairFlow collaboration diagrams (content + grid layout)."""
from bpmngen import Diagram

SERVICE, TECH, LEITUNG, DISPO = "Service / Annahme", "Techniker", "Werkstattleitung", "Ersatzteil-Disposition"
KUNDE, LIEF = "Kunde", "Lieferant"

DIAGRAMS = []


def build_01():
    d = Diagram("01", "KI-Sofortdiagnose und Voranmeldung", [SERVICE, DISPO, LEITUNG], pools_top=[KUNDE], shift=2,
                doc="Der Kunde laedt in der RepairFlow-App Foto, Video oder Tonaufnahme des defekten Geraets hoch; daraus entsteht "
                    "eine Voranmeldung. RepairFlow erstellt automatisch Diagnosevorschlag, Vorab-Kostenvoranschlag, prueft die "
                    "Teileverfuegbarkeit ueber alle Filialen und schlaegt Filiale und Termin vor. Bestaetigt der Kunde, werden "
                    "Ersatzteile vorreserviert; lehnt er ab oder reagiert er nicht, wird die Voranmeldung verworfen.")
    n, f = d.node, d.flow
    n("Start_01", "start", "Anfrage eingegangen", 0, 0, trigger="message", msg="Sofortdiagnose-Anfrage")
    n("T01_Voranmeldung", "service", "Voranmeldung anlegen", 0, 1)
    n("Merge_01", "xor", "", 0, 2)
    n("T01_Medien", "service", "Medienanhang prüfen und speichern", 0, 3)
    n("GW01_Auswertbar", "xor", "Medien auswertbar?", 0, 4)
    n("T01_Rueckfrage", "send", "Bessere Aufnahme anfordern", 0, 5, 1)
    n("GW01_Antwort", "event", "", 0, 6, 1)
    n("E01_Neu", "catch", "Neue Aufnahme erhalten", 0, 7, 1, trigger="message", msg="Neue Aufnahme")
    n("E01_Timer1", "catch", "7 Tage verstrichen", 0, 7, 3, trigger="timer", duration="P7D")
    n("T01_KI", "businessRule", "KI-Diagnosevorschlag erstellen", 0, 8, type="repairflow.ki-diagnose")
    n("T01_VorabKVA", "service", "Vorab-Kostenvoranschlag berechnen", 0, 9)
    n("T01_Verfuegbarkeit", "service", "Verfügbarkeit in allen Filialen prüfen", 1, 10)
    n("T01_Termin", "service", "Filiale und Terminvorschlag ermitteln", 2, 10)
    n("T01_Senden", "send", "Sofortdiagnose an Kunde senden", 0, 11)
    n("GW01_Warten", "event", "", 0, 12)
    n("E01_Bestaetigt", "catch", "Voranmeldung bestätigt", 0, 13, trigger="message", msg="Voranmeldung bestätigt")
    n("E01_Abgelehnt", "catch", "Termin abgelehnt", 0, 14, 1, trigger="message", msg="Termin abgelehnt")
    n("E01_Timer", "catch", "7 Tage verstrichen", 0, 13, 2, trigger="timer", duration="P7D")
    n("Merge_01v", "xor", "", 0, 15, 3)
    n("T01_Verwerfen", "service", "Voranmeldung verwerfen", 0, 18, 3)
    n("T01_Markieren", "service", "Voranmeldung als bestätigt markieren", 0, 15)
    n("T01_Reservieren", "service", "Ersatzteile vorreservieren", 1, 16)
    n("T01_Bestaetigung", "send", "Bestätigung an Kunde senden", 0, 17)
    n("Join_01", "xor", "", 0, 19)
    n("End_01", "end", "Sofortdiagnose abgeschlossen", 0, 20)
    # ---- Kunde (eigener Ablauf in der RepairFlow-App)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K01_Start", "start", "Gerät defekt", 0)
    k("K01_Aufnahme", "manual", "Foto, Video oder Ton aufnehmen", 1)
    k("K01_Senden", "send", "Anfrage in der App senden", 2)
    k("K01_Merge", "xor", "", 3)
    k("K01_Warten", "event", "", 4)
    k("K01_Rueckfrage", "catch", "Rückfrage erhalten", 6, 1, trigger="message")
    k("K01_Neu", "send", "Neue Aufnahme senden", 7, 1)
    k("K01_Diagnose", "catch", "Diagnose erhalten", 11, trigger="message")
    k("K01_Pruefen", "user", "Diagnose und Vorab-KVA prüfen", 12)
    k("K01_GW", "xor", "Termin annehmen?", 13)
    k("K01_Bestaetigen", "send", "Voranmeldung bestätigen", 14)
    k("K01_Ablehnen", "send", "Termin ablehnen", 15, 1)
    k("K01_Bestaetigung", "catch", "Bestätigung erhalten", 17, trigger="message")
    k("K01_Join", "xor", "", 18, 1)
    k("K01_End", "end", "Anfrage erledigt", 19, 1)
    f("K01_Start", "K01_Aufnahme"); f("K01_Aufnahme", "K01_Senden"); f("K01_Senden", "K01_Merge"); f("K01_Merge", "K01_Warten")
    f("K01_Warten", "K01_Rueckfrage"); f("K01_Warten", "K01_Diagnose")
    f("K01_Rueckfrage", "K01_Neu"); f("K01_Neu", "K01_Merge", loop=1)
    f("K01_Diagnose", "K01_Pruefen"); f("K01_Pruefen", "K01_GW")
    f("K01_GW", "K01_Bestaetigen", "ja", "=terminAngenommen")
    f("K01_GW", "K01_Ablehnen", "nein", "=not(terminAngenommen)")
    f("K01_Bestaetigen", "K01_Bestaetigung"); f("K01_Bestaetigung", "K01_Join"); f("K01_Ablehnen", "K01_Join"); f("K01_Join", "K01_End")
    f("Start_01", "T01_Voranmeldung"); f("T01_Voranmeldung", "Merge_01"); f("Merge_01", "T01_Medien"); f("T01_Medien", "GW01_Auswertbar")
    f("GW01_Auswertbar", "T01_KI", "ja", "=medienAuswertbar")
    f("GW01_Auswertbar", "T01_Rueckfrage", "nein", "=not(medienAuswertbar)")
    f("T01_Rueckfrage", "GW01_Antwort"); f("GW01_Antwort", "E01_Neu"); f("GW01_Antwort", "E01_Timer1")
    f("E01_Neu", "Merge_01", loop=1); f("E01_Timer1", "Merge_01v")
    f("T01_KI", "T01_VorabKVA"); f("T01_VorabKVA", "T01_Verfuegbarkeit"); f("T01_Verfuegbarkeit", "T01_Termin")
    f("T01_Termin", "T01_Senden"); f("T01_Senden", "GW01_Warten")
    f("GW01_Warten", "E01_Bestaetigt"); f("GW01_Warten", "E01_Abgelehnt"); f("GW01_Warten", "E01_Timer")
    f("E01_Abgelehnt", "Merge_01v"); f("E01_Timer", "Merge_01v"); f("Merge_01v", "T01_Verwerfen"); f("T01_Verwerfen", "Join_01")
    f("E01_Bestaetigt", "T01_Markieren"); f("T01_Markieren", "T01_Reservieren")
    f("T01_Reservieren", "T01_Bestaetigung"); f("T01_Bestaetigung", "Join_01"); f("Join_01", "End_01")
    d.msg("K01_Senden", "Start_01", "Foto / Video / Ton + Symptome")
    d.msg("T01_Rueckfrage", "K01_Rueckfrage", "Rückfrage")
    d.msg("K01_Neu", "E01_Neu", "Neue Aufnahme")
    d.msg("T01_Senden", "K01_Diagnose", "Diagnose, Vorab-KVA, Termin")
    d.msg("K01_Bestaetigen", "E01_Bestaetigt", "Bestätigung")
    d.msg("K01_Ablehnen", "E01_Abgelehnt", "Ablehnung")
    d.msg("T01_Bestaetigung", "K01_Bestaetigung", "Bestätigung der Voranmeldung")
    d.data("T01_Voranmeldung", "Voranmeldung")
    d.data("T01_Medien", "Medienanhang")
    d.data("T01_KI", "KI-Diagnose-vorschlag")
    d.data("T01_VorabKVA", "Kosten-voranschlag [vorläufig]")
    d.data("T01_Reservieren", "Ersatzteil-Reservierung [vorreserviert]")
    d.store("T01_Verfuegbarkeit", dir="in")
    return d


def build_02():
    d = Diagram("02", "Auftragsannahme, Geräteregistrierung und Terminplanung", [SERVICE, LEITUNG], pools_top=[KUNDE], shift=2,
                doc="Der Kunde bringt das Geraet in die Filiale. Daten aus einer Voranmeldung werden uebernommen, das Geraet "
                    "registriert, der Reparaturauftrag angelegt und von der Werkstattleitung eingeplant (Kapazitaet, bei Bedarf Umleitung "
                    "an eine andere Filiale, Techniker, Termin).")
    n, f = d.node, d.flow
    n("Start_02", "start", "Kunde erschienen", 0, 0, trigger="message", msg="Gerät abgegeben")
    n("GW02_Voranmeldung", "xor", "Voranmeldung vorhanden?", 0, 1)
    n("T02_Uebernehmen", "service", "Voranmeldungsdaten übernehmen", 0, 2)
    n("T02_Kundendaten", "user", "Kundendaten erfassen", 0, 2, 1)
    n("Join_02a", "xor", "", 0, 3)
    n("T02_Geraet", "user", "Gerät registrieren", 0, 4)
    n("T02_Symptome", "user", "Symptome und Zubehör dokumentieren", 0, 5)
    n("T02_Sicht", "manual", "Sichtprüfung durchführen", 0, 6)
    n("T02_Auftrag", "service", "Reparaturauftrag anlegen", 0, 7)
    n("T02_Auslastung", "service", "Werkstattauslastung prüfen", 1, 8)
    n("GW02_Kapazitaet", "xor", "Kapazität in Filiale frei?", 1, 9)
    n("T02_Umleiten", "user", "Auftrag an andere Filiale umleiten", 1, 10, 1)
    n("Join_02b", "xor", "", 1, 11)
    n("T02_Techniker", "user", "Techniker zuweisen", 1, 12)
    n("T02_Termin", "user", "Werkstatttermin festlegen", 1, 13)
    n("T02_Beleg", "send", "Annahmebeleg und Termin an Kunde senden", 0, 14)
    n("T02_Einlagern", "manual", "Gerät kennzeichnen und einlagern", 0, 15)
    n("End_02", "end", "Auftrag angenommen", 0, 16)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K02_Start", "start", "Reparatur gewünscht", 0)
    k("K02_Bringen", "manual", "Gerät in die Filiale bringen", 1)
    k("K02_Abgeben", "send", "Gerät abgeben und Auftrag erteilen", 2)
    k("K02_Beleg", "receive", "Annahmebeleg und Termin empfangen", 16)
    k("K02_End", "end", "Auftrag erteilt", 17)
    f("K02_Start", "K02_Bringen"); f("K02_Bringen", "K02_Abgeben"); f("K02_Abgeben", "K02_Beleg"); f("K02_Beleg", "K02_End")
    f("Start_02", "GW02_Voranmeldung")
    f("GW02_Voranmeldung", "T02_Uebernehmen", "ja", "=voranmeldungVorhanden")
    f("GW02_Voranmeldung", "T02_Kundendaten", "nein", "=not(voranmeldungVorhanden)")
    f("T02_Uebernehmen", "Join_02a"); f("T02_Kundendaten", "Join_02a")
    f("Join_02a", "T02_Geraet"); f("T02_Geraet", "T02_Symptome"); f("T02_Symptome", "T02_Sicht")
    f("T02_Sicht", "T02_Auftrag"); f("T02_Auftrag", "T02_Auslastung"); f("T02_Auslastung", "GW02_Kapazitaet")
    f("GW02_Kapazitaet", "Join_02b", "ja", "=kapazitaetFrei")
    f("GW02_Kapazitaet", "T02_Umleiten", "nein", "=not(kapazitaetFrei)")
    f("T02_Umleiten", "Join_02b"); f("Join_02b", "T02_Techniker"); f("T02_Techniker", "T02_Termin")
    f("T02_Termin", "T02_Beleg"); f("T02_Beleg", "T02_Einlagern"); f("T02_Einlagern", "End_02")
    d.msg("K02_Abgeben", "Start_02", "Gerät + Auftragswunsch")
    d.msg("T02_Beleg", "K02_Beleg", "Annahmebeleg, Termin")
    d.data("T02_Uebernehmen", "Voranmeldung", dir="in")
    d.data("T02_Geraet", "Geraet")
    d.data("T02_Auftrag", "Reparatur-auftrag [angenommen]")
    d.store("T02_Auftrag")
    d.store("T02_Auslastung", name="Technikerplan", dir="in")
    d.store("T02_Termin", name="Technikerplan")
    return d


def build_03():
    d = Diagram("03", "Fehlerdiagnose", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Der Techniker prueft den KI-Diagnosevorschlag, fuehrt Funktionstest und Messung durch (bei Bedarf eine "
                    "erweiterte Pruefung), dokumentiert den Fehlerbefund und legt den Ersatzteilbedarf fest. RepairFlow bewertet "
                    "die Wirtschaftlichkeit der Reparatur; ist sie nicht gegeben (Totalschaden, Fehler nicht reproduzierbar), "
                    "wird der Auftrag abgelehnt und ueber Prozess 08 mit Diagnosepauschale zur Abholung gebracht.")
    n, f = d.node, d.flow
    n("Start_03", "start", "Auftrag eingeplant", 1, 0)
    n("T03_Status", "service", "Auftragsstatus auf 'in Diagnose' setzen", 1, 1)
    n("T03_KI", "user", "KI-Diagnosevorschlag sichten", 1, 2)
    n("T03_Test", "user", "Funktionstest durchführen und Messwerte erfassen", 1, 3)
    n("GW03_Repro", "xor", "Fehler reproduzierbar?", 1, 4)
    n("T03_Erweitert", "manual", "Erweiterte Prüfung durchführen", 1, 5, 1)
    n("Join_03r", "xor", "", 1, 6)
    n("T03_Befund", "user", "Fehlerbefund dokumentieren", 1, 7)
    n("T03_Teile", "user", "Ersatzteilbedarf festlegen", 1, 8)
    n("T03_Wirtschaft", "businessRule", "Wirtschaftlichkeit der Reparatur prüfen", 1, 9, type="repairflow.wirtschaftlichkeit")
    n("GW03_Wirtschaft", "xor", "Reparatur wirtschaftlich?", 1, 10, label="left")
    n("T03_Absage", "send", "Kunde über Reparaturabsage informieren", 0, 11)
    n("T03_Schliessen", "service", "Auftragsstatus auf 'abgelehnt' setzen", 0, 12)
    n("T03_Abholung", "call", "08 Abholung abwickeln", 0, 13, called="Proc_08")
    n("T03_Aufwand", "user", "Reparaturaufwand schätzen", 1, 11)
    n("T03_Abschluss", "service", "Diagnose abschließen und KVA anstoßen", 1, 12)
    n("Join_03", "xor", "", 1, 14)
    n("End_03", "end", "Diagnose abgeschlossen", 1, 15)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K03_Start", "start", "Reparaturabsage erhalten", 11, trigger="message")
    k("K03_Planen", "manual", "Abholung des Geräts planen", 12)
    k("K03_End", "end", "Absage verarbeitet", 13)
    f("K03_Start", "K03_Planen"); f("K03_Planen", "K03_End")
    f("Start_03", "T03_Status"); f("T03_Status", "T03_KI"); f("T03_KI", "T03_Test")
    f("T03_Test", "GW03_Repro")
    f("GW03_Repro", "Join_03r", "ja", "=fehlerReproduzierbar")
    f("GW03_Repro", "T03_Erweitert", "nein", "=not(fehlerReproduzierbar)")
    f("T03_Erweitert", "Join_03r"); f("Join_03r", "T03_Befund")
    f("T03_Befund", "T03_Teile"); f("T03_Teile", "T03_Wirtschaft"); f("T03_Wirtschaft", "GW03_Wirtschaft")
    f("GW03_Wirtschaft", "T03_Aufwand", "ja", "=reparaturWirtschaftlich")
    f("GW03_Wirtschaft", "T03_Absage", "nein", "=not(reparaturWirtschaftlich)")
    f("T03_Absage", "T03_Schliessen"); f("T03_Schliessen", "T03_Abholung"); f("T03_Abholung", "Join_03")
    f("T03_Aufwand", "T03_Abschluss"); f("T03_Abschluss", "Join_03"); f("Join_03", "End_03")
    d.msg("T03_Absage", "K03_Start", "Reparaturabsage (Totalschaden / kein Befund)")
    d.data("T03_Status", "Reparatur-auftrag [in Diagnose]")
    d.data("T03_KI", "KI-Diagnose-vorschlag", dir="in")
    d.data("T03_Befund", "Fehlerbefund")
    d.data("T03_Schliessen", "Reparatur-auftrag [abgelehnt]")
    d.store("T03_Status")
    return d


def build_04():
    d = Diagram("04", "Kostenvoranschlag und Kundenfreigabe", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Aus dem Fehlerbefund entsteht der Kostenvoranschlag. RepairFlow sendet ihn an den Kunden und wartet auf "
                    "Freigabe oder Ablehnung; bleibt die Reaktion aus, wird der KVA mit Erinnerung erneut gesendet, nach der "
                    "dritten Erinnerung gilt er als abgelehnt. Abgelehnte Auftraege gehen ueber Prozess 08 mit Diagnosepauschale "
                    "zur Abholung.")
    n, f = d.node, d.flow
    n("Start_04", "start", "KVA angestoßen", 1, 0)
    n("T04_Positionen", "user", "KVA-Positionen erfassen", 1, 1)
    n("T04_Preise", "service", "Ersatzteilpreise übernehmen", 1, 2)
    n("T04_Berechnen", "service", "Kostenvoranschlag berechnen", 1, 3)
    n("T04_Pruefen", "user", "Kostenvoranschlag prüfen", 0, 4)
    n("T04_Status", "service", "Auftragsstatus auf 'KVA offen' setzen", 0, 5)
    n("Merge_04", "xor", "", 0, 6)
    n("T04_Senden", "send", "Kostenvoranschlag an Kunde senden", 0, 7)
    n("GW04_Warten", "event", "", 0, 8)
    n("E04_Freigabe", "catch", "Freigabe erhalten", 0, 10, trigger="message", msg="KVA-Freigabe")
    n("E04_Ablehnung", "catch", "Ablehnung erhalten", 0, 9, 1, trigger="message", msg="KVA-Ablehnung")
    n("E04_Timer", "catch", "3 Tage verstrichen", 0, 9, 2, trigger="timer", duration="P3D")
    n("T04_Erinnerung", "service", "Erinnerung protokollieren", 0, 10, 2)
    n("GW04_Dritte", "xor", "Dritte Erinnerung ohne Antwort?", 0, 11, 2)
    n("Merge_04a", "xor", "", 0, 12, 1)
    n("T04_Freigegeben", "service", "Auftragsstatus auf 'freigegeben' setzen", 0, 11)
    n("T04_Dispo", "call", "05 Ersatzteile disponieren", 0, 12, called="Proc_05")
    n("T04_Abgelehnt", "service", "Auftragsstatus auf 'abgelehnt' setzen", 0, 13, 1)
    n("T04_Abholung", "call", "08 Abholung abwickeln", 0, 14, 1, called="Proc_08")
    n("Join_04", "xor", "", 0, 15)
    n("End_04", "end", "KVA-Entscheidung verarbeitet", 0, 16)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K04_Start", "start", "KVA erhalten", 7, trigger="message")
    k("K04_Pruefen", "user", "KVA in der App prüfen", 8)
    k("K04_GW", "xor", "KVA freigeben?", 9)
    k("K04_Freigabe", "send", "Freigabe senden", 10)
    k("K04_Ablehnung", "send", "Ablehnung senden", 9, 1)
    k("K04_Join", "xor", "", 11)
    k("K04_End", "end", "KVA entschieden", 12)
    f("K04_Start", "K04_Pruefen"); f("K04_Pruefen", "K04_GW")
    f("K04_GW", "K04_Freigabe", "ja", "=kvaFreigeben")
    f("K04_GW", "K04_Ablehnung", "nein", "=not(kvaFreigeben)")
    f("K04_Freigabe", "K04_Join"); f("K04_Ablehnung", "K04_Join"); f("K04_Join", "K04_End")
    f("Start_04", "T04_Positionen"); f("T04_Positionen", "T04_Preise"); f("T04_Preise", "T04_Berechnen")
    f("T04_Berechnen", "T04_Pruefen"); f("T04_Pruefen", "T04_Status"); f("T04_Status", "Merge_04")
    f("Merge_04", "T04_Senden"); f("T04_Senden", "GW04_Warten")
    f("GW04_Warten", "E04_Freigabe"); f("GW04_Warten", "E04_Ablehnung"); f("GW04_Warten", "E04_Timer")
    f("E04_Timer", "T04_Erinnerung"); f("T04_Erinnerung", "GW04_Dritte")
    f("GW04_Dritte", "Merge_04", "nein", "=erinnerungen < 3", loop=1)
    f("GW04_Dritte", "Merge_04a", "ja", "=erinnerungen >= 3", via="right")
    f("E04_Freigabe", "T04_Freigegeben"); f("T04_Freigegeben", "T04_Dispo"); f("T04_Dispo", "Join_04")
    f("E04_Ablehnung", "Merge_04a"); f("Merge_04a", "T04_Abgelehnt"); f("T04_Abgelehnt", "T04_Abholung")
    f("T04_Abholung", "Join_04"); f("Join_04", "End_04")
    d.msg("T04_Senden", "K04_Start", "KVA (ggf. mit Erinnerung)")
    d.msg("K04_Freigabe", "E04_Freigabe", "Freigabe")
    d.msg("K04_Ablehnung", "E04_Ablehnung", "Ablehnung")
    d.data("T04_Positionen", "Kva-Position")
    d.data("T04_Berechnen", "Kosten-voranschlag [Entwurf]")
    d.data("T04_Status", "Reparatur-auftrag [KVA offen]")
    d.data("T04_Senden", "Kosten-voranschlag [versendet]")
    d.data("T04_Freigegeben", "Reparatur-auftrag [freigegeben]", pos="bottom")
    d.data("T04_Abgelehnt", "Reparatur-auftrag [abgelehnt]", pos="bottom")
    d.store("T04_Preise", dir="in")
    return d


def build_05():
    d = Diagram("05", "Ersatzteil-Verfügbarkeit und Reservierung", [SERVICE, DISPO], pools_top=[KUNDE],
                doc="Nach der KVA-Freigabe prueft RepairFlow je Ersatzteil den Bestand der eigenen und der anderen Filialen, "
                    "reserviert Teile, fordert Umlagerungen an und markiert Fehlteile fuer die Bestellung. Unterschreitet ein "
                    "Bestand den Meldebestand, entsteht ein Nachbestellvorschlag; er bleibt im Status Vorschlag und wird mit "
                    "der naechsten Bestellung in Prozess 06 gebuendelt, ohne die Reparatur aufzuhalten. Der Kunde erhaelt "
                    "den voraussichtlichen Reparaturbeginn; nur Fehlteile werden direkt ueber Prozess 06 bestellt.")
    n, f = d.node, d.flow
    n("Start_05", "start", "KVA freigegeben", 1, 0)
    n("T05_Teileliste", "service", "Teileliste aus KVA übernehmen", 1, 1)
    n("Sub_05", "subprocess", "Verfügbarkeit je Ersatzteil prüfen", 1, 2, multi=True, collection="=ersatzteile", element="ersatzteil")
    n("S05_Start", "start", "Ersatzteil ausgewählt", 1, 2, parent="Sub_05")
    n("S05_Eigen", "service", "Bestand eigene Filiale prüfen", 1, 3, parent="Sub_05")
    n("GW05_Eigen", "xor", "Eigener Bestand ausreichend?", 1, 4, parent="Sub_05")
    n("S05_Reservieren", "service", "Teil in eigener Filiale reservieren", 1, 5, parent="Sub_05")
    n("S05_Andere", "service", "Bestand anderer Filialen prüfen", 1, 5, 1, parent="Sub_05")
    n("GW05_Andere", "xor", "In anderer Filiale verfügbar?", 1, 6, 1, parent="Sub_05")
    n("S05_ResAndere", "service", "Teil in anderer Filiale reservieren", 1, 7, 1, parent="Sub_05")
    n("S05_Umlagerung", "user", "Umlagerung anfordern", 1, 8, 1, parent="Sub_05")
    n("S05_Fehlteil", "service", "Teil als Fehlteil markieren", 1, 7, 2, parent="Sub_05")
    n("S05_Join", "xor", "", 1, 9, parent="Sub_05")
    n("S05_End", "end", "Teil disponiert", 1, 10, parent="Sub_05")
    n("T05_Bestaetigen", "service", "Reservierungen bestätigen", 1, 11)
    n("T05_Meldebestand", "businessRule", "Meldebestand prüfen", 1, 12, type="repairflow.meldebestand")
    n("GW05_Meldebestand", "xor", "Meldebestand unterschritten?", 1, 13)
    n("T05_Nachbestellung", "service", "Nachbestellvorschlag erzeugen", 1, 14, 1)
    n("Join_05m", "xor", "", 1, 15)
    n("T05_Beginn", "service", "Voraussichtlichen Reparaturbeginn ermitteln", 0, 16)
    n("T05_Info", "send", "Kunde über Reparaturbeginn informieren", 0, 17)
    n("GW05_Fehlteile", "xor", "Fehlteile vorhanden?", 1, 18)
    n("T05_Bestellen", "call", "06 Ersatzteile bestellen", 1, 19, 1, called="Proc_06")
    n("Join_05", "xor", "", 1, 20)
    n("End_05", "end", "Ersatzteile disponiert", 1, 21)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K05_Start", "start", "Reparaturtermin erhalten", 17, trigger="message")
    k("K05_Vormerken", "manual", "Reparaturbeginn vormerken", 18)
    k("K05_End", "end", "Termin bekannt", 19)
    f("K05_Start", "K05_Vormerken"); f("K05_Vormerken", "K05_End")
    f("Start_05", "T05_Teileliste"); f("T05_Teileliste", "Sub_05")
    f("S05_Start", "S05_Eigen"); f("S05_Eigen", "GW05_Eigen")
    f("GW05_Eigen", "S05_Reservieren", "ja", "=bestandAusreichend")
    f("GW05_Eigen", "S05_Andere", "nein", "=not(bestandAusreichend)")
    f("S05_Andere", "GW05_Andere")
    f("GW05_Andere", "S05_ResAndere", "ja", "=andereFilialeVerfuegbar")
    f("GW05_Andere", "S05_Fehlteil", "nein", "=not(andereFilialeVerfuegbar)")
    f("S05_ResAndere", "S05_Umlagerung")
    f("S05_Reservieren", "S05_Join"); f("S05_Umlagerung", "S05_Join"); f("S05_Fehlteil", "S05_Join")
    f("S05_Join", "S05_End")
    f("Sub_05", "T05_Bestaetigen")
    f("T05_Bestaetigen", "T05_Meldebestand"); f("T05_Meldebestand", "GW05_Meldebestand")
    f("GW05_Meldebestand", "T05_Nachbestellung", "ja", "=meldebestandUnterschritten")
    f("GW05_Meldebestand", "Join_05m", "nein", "=not(meldebestandUnterschritten)")
    f("T05_Nachbestellung", "Join_05m"); f("Join_05m", "T05_Beginn"); f("T05_Beginn", "T05_Info"); f("T05_Info", "GW05_Fehlteile")
    f("GW05_Fehlteile", "T05_Bestellen", "ja", "=fehlteileVorhanden")
    f("GW05_Fehlteile", "Join_05", "nein", "=not(fehlteileVorhanden)")
    f("T05_Bestellen", "Join_05"); f("Join_05", "End_05")
    d.msg("T05_Info", "K05_Start", "Voraussichtlicher Reparaturbeginn")
    d.data("T05_Teileliste", "Kosten-voranschlag [freigegeben]", dir="in")
    d.data("T05_Bestaetigen", "Ersatzteil-Reservierung [reserviert]")
    d.data("T05_Meldebestand", "Lagerbestand", dir="in", pos="bottom")
    d.data("T05_Nachbestellung", "Lieferanten-bestellung [Vorschlag]", pos="bottom")
    d.store("T05_Teileliste", dir="in")
    return d


def build_06():
    d = Diagram("06", "Ersatzteil-Bestellung beim Lieferanten", [LEITUNG, DISPO, SERVICE], pools_top=[LIEF], pools_bottom=[KUNDE],
                doc="Fehlteile eines Reparaturauftrags werden zusammen mit offenen Nachbestellvorschlaegen zu einer "
                    "Lieferantenbestellung gebuendelt, bei Bedarf von der Werkstattleitung freigegeben und an den Lieferanten "
                    "gesendet. Kommt binnen 3 Tagen keine Auftragsbestaetigung oder kann der Lieferant nicht liefern, wird die "
                    "Bestellung storniert und ein alternativer Lieferant gesucht. Bleibt die Lieferung 14 Tage aus, wird sie "
                    "angemahnt. Nach dem Wareneingang werden die Fehlteile dem Auftrag zugeordnet, Nachbestellteile gehen ins "
                    "Lager; bei Verzoegerungen informiert RepairFlow den Kunden. Mangelhafte Lieferungen laufen ueber Prozess "
                    "10: Eine Ersatzlieferung wird vor der Zuordnung geprueft, bei Gutschrift wird neu bestellt, solange das "
                    "Teil noch benoetigt wird.")
    n, f = d.node, d.flow
    n("Start_06", "start", "Bestellbedarf gemeldet", 1, 0)
    n("T06_Buendeln", "service", "Fehlteile und Nachbestellvorschläge bündeln", 1, 1)
    n("Merge_06", "xor", "", 1, 2)
    n("T06_Lieferant", "user", "Lieferanten auswählen", 1, 3)
    n("T06_Bestellung", "service", "Bestellung beim Lieferanten anlegen", 1, 4)
    n("GW06_Grenze", "xor", "Über Freigabegrenze?", 1, 5)
    n("T06_Freigabe", "user", "Bestellung freigeben", 0, 6)
    n("Join_06a", "xor", "", 1, 7)
    n("T06_Senden", "send", "Bestellung an Lieferanten senden", 1, 8)
    n("GW06_AB", "event", "", 1, 9)
    n("E06_AB", "catch", "Auftragsbestätigung erhalten", 1, 10, trigger="message", msg="Auftragsbestätigung")
    n("E06_ABTimer", "catch", "3 Tage verstrichen", 1, 10, 1, trigger="timer", duration="P3D")
    n("GW06_Lieferbar", "xor", "Bestätigt und lieferbar?", 1, 11)
    n("Merge_06s", "xor", "", 1, 11, 1)
    n("T06_Storno", "service", "Bestellung stornieren", 1, 12, 1)
    n("T06_Alternative", "user", "Alternativen Lieferanten suchen", 1, 13, 1)
    n("GW06_Alt", "xor", "Alternativer Lieferant verfügbar?", 1, 14, 1)
    n("T06_Termin", "service", "Liefertermin hinterlegen", 1, 12)
    n("GW06_Verzoegert", "xor", "Reparatur verzögert?", 1, 15)
    n("T06_KundeInfo", "send", "Kunde über Verzögerung informieren", 2, 16)
    n("Join_06b", "xor", "", 1, 17)
    n("Merge_06m", "xor", "", 1, 18)
    n("GW06_Lief", "event", "", 1, 19)
    n("E06_Lieferung", "catch", "Lieferung erhalten", 1, 20, trigger="message", msg="Lieferung")
    n("E06_LiefTimer", "catch", "14 Tage verstrichen", 1, 20, 1, trigger="timer", duration="P14D")
    n("T06_Mahnen", "send", "Lieferung anmahnen", 1, 21, 2)
    n("T06_Wareneingang", "user", "Wareneingang prüfen und buchen", 1, 22)
    n("GW06_Mangelfrei", "xor", "Lieferung mangelfrei?", 1, 23)
    n("T06_Retoure", "call", "10 Retoure abwickeln", 1, 24, 1, called="Proc_10")
    n("GW06_Ersatz", "xor", "Ersatz geliefert?", 1, 25, 1)
    n("T06_ErsatzPruefen", "user", "Ersatzlieferung prüfen", 1, 26, 1)
    n("GW06_Bedarf", "xor", "Teil weiterhin benötigt?", 1, 26, 2)
    n("Join_06c", "xor", "", 1, 27)
    n("T06_Zuordnen", "service", "Fehlteile dem Reparaturauftrag zuordnen", 1, 28)
    n("Join_06d", "xor", "", 1, 29, 3)
    n("End_06", "end", "Bestellung abgeschlossen", 1, 30, 3)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K06_Start", "start", "Verzögerungsinfo erhalten", 16, trigger="message")
    k("K06_Kenntnis", "manual", "Neuen Liefertermin zur Kenntnis nehmen", 17)
    k("K06_End", "end", "Info erhalten", 18)
    f("K06_Start", "K06_Kenntnis"); f("K06_Kenntnis", "K06_End")
    f("Start_06", "T06_Buendeln"); f("T06_Buendeln", "Merge_06"); f("Merge_06", "T06_Lieferant")
    f("T06_Lieferant", "T06_Bestellung"); f("T06_Bestellung", "GW06_Grenze")
    f("GW06_Grenze", "T06_Freigabe", "ja", "=bestellwert > freigabegrenze")
    f("GW06_Grenze", "Join_06a", "nein", "=bestellwert <= freigabegrenze")
    f("T06_Freigabe", "Join_06a"); f("Join_06a", "T06_Senden"); f("T06_Senden", "GW06_AB")
    f("GW06_AB", "E06_AB"); f("GW06_AB", "E06_ABTimer")
    f("E06_AB", "GW06_Lieferbar"); f("E06_ABTimer", "Merge_06s")
    f("GW06_Lieferbar", "T06_Termin", "ja", "=bestaetigt and lieferbar")
    f("GW06_Lieferbar", "Merge_06s", "nein", "=not(bestaetigt and lieferbar)")
    f("Merge_06s", "T06_Storno"); f("T06_Storno", "T06_Alternative"); f("T06_Alternative", "GW06_Alt")
    f("GW06_Alt", "Merge_06", "ja", "=alternativeVerfuegbar", loop=1)
    f("GW06_Alt", "Join_06d", "nein", "=not(alternativeVerfuegbar)")
    f("T06_Termin", "GW06_Verzoegert")
    f("GW06_Verzoegert", "T06_KundeInfo", "ja", "=reparaturVerzoegert")
    f("GW06_Verzoegert", "Join_06b", "nein", "=not(reparaturVerzoegert)")
    f("T06_KundeInfo", "Join_06b"); f("Join_06b", "Merge_06m"); f("Merge_06m", "GW06_Lief")
    f("GW06_Lief", "E06_Lieferung"); f("GW06_Lief", "E06_LiefTimer")
    f("E06_LiefTimer", "T06_Mahnen"); f("T06_Mahnen", "Merge_06m", loop=1)
    f("E06_Lieferung", "T06_Wareneingang"); f("T06_Wareneingang", "GW06_Mangelfrei")
    f("GW06_Mangelfrei", "Join_06c", "ja", "=lieferungMangelfrei")
    f("GW06_Mangelfrei", "T06_Retoure", "nein", "=not(lieferungMangelfrei)")
    f("T06_Retoure", "GW06_Ersatz")
    f("GW06_Ersatz", "T06_ErsatzPruefen", "ja", "=ersatzGeliefert")
    f("GW06_Ersatz", "GW06_Bedarf", "nein", "=not(ersatzGeliefert)")
    f("T06_ErsatzPruefen", "Join_06c")
    f("GW06_Bedarf", "Merge_06", "ja", "=teilBenoetigt", loop=3)
    f("GW06_Bedarf", "Join_06d", "nein", "=not(teilBenoetigt)")
    f("Join_06c", "T06_Zuordnen"); f("T06_Zuordnen", "Join_06d"); f("Join_06d", "End_06")
    d.msg("T06_Senden", LIEF, "Bestellung")
    d.msg(LIEF, "E06_AB", "Auftrags-bestätigung, Liefertermin")
    d.msg(LIEF, "E06_Lieferung", "Lieferung + Lieferschein")
    d.msg("T06_Mahnen", LIEF, "Mahnung")
    d.msg("T06_KundeInfo", "K06_Start", "Info: neuer Liefertermin")
    d.data("T06_Buendeln", "Lieferanten-bestellung [Vorschlag]", dir="in")
    d.data("T06_Lieferant", "Lieferant", dir="in")
    d.data("T06_Bestellung", "Lieferanten-bestellung [offen]")
    d.data("T06_Storno", "Lieferanten-bestellung [storniert]", pos="bottom")
    d.data("T06_Termin", "Reparatur-auftrag [Teile bestellt]")
    d.data("T06_Wareneingang", "Lagerbestand")
    d.store("T06_Wareneingang")
    return d


def build_07():
    d = Diagram("07", "Reparaturdurchführung und Arbeitszeiterfassung", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Der Techniker entnimmt die reservierten Teile und arbeitet die Reparaturschritte mit Zeiterfassung ab. "
                    "Zusatzbefunde fuehren zu einem Nachtrags-KVA, den der Kunde freigeben muss; die Teile fuer einen freigegebenen "
                    "Nachtrag werden ueber Prozess 05 disponiert und entnommen. Ohne Antwort innerhalb von drei Tagen gilt der "
                    "Nachtrag als abgelehnt. Nach Endkontrolle wird der Auftrag auf 'fertig' gesetzt; scheitert auch die zweite "
                    "Nacharbeit, wird die Reparatur abgebrochen und der Auftrag auf 'abgelehnt' gesetzt. Auch Nacharbeiten "
                    "aus Prozess 09 laufen ueber diesen Prozess.")
    n, f = d.node, d.flow
    n("Start_07", "start", "Ersatzteile disponiert", 1, 0)
    n("T07_Status", "service", "Auftragsstatus auf 'in Reparatur' setzen", 1, 1)
    n("Merge_07e", "xor", "", 1, 2)
    n("T07_Entnahme", "user", "Reservierte Ersatzteile entnehmen", 1, 3)
    n("Merge_07", "xor", "", 1, 4)
    n("T07_Start", "user", "Reparaturschritt starten und Zeit erfassen", 1, 5)
    n("T07_Ausfuehren", "manual", "Reparaturschritt ausführen", 1, 6)
    n("T07_Doku", "user", "Schritt dokumentieren und Zeit stoppen", 1, 7)
    n("GW07_Weitere", "xor", "Weitere Schritte offen?", 1, 8)
    n("GW07_Zusatz", "xor", "Zusatzbefund festgestellt?", 1, 9)
    n("T07_Nachtrag", "user", "Nachtrags-KVA erstellen", 1, 10, 2)
    n("T07_NachtragSenden", "send", "Nachtrag an Kunde senden", 0, 11)
    n("GW07_Warten", "event", "", 0, 12)
    n("E07_Entscheidung", "catch", "Kundenentscheidung erhalten", 0, 13, trigger="message", msg="Nachtragsentscheidung")
    n("E07_Timer", "catch", "3 Tage verstrichen", 0, 13, 1, trigger="timer", duration="P3D")
    n("GW07_Nachtrag", "xor", "Nachtrag freigegeben?", 0, 14)
    n("T07_Teile", "call", "05 Ersatzteile disponieren", 0, 15, called="Proc_05")
    n("Merge_07n", "xor", "", 0, 15, 1)
    n("T07_Abgelehnt", "service", "Nachtrag auf 'abgelehnt' setzen", 0, 16, 1)
    n("Join_07", "xor", "", 1, 17)
    n("T07_Endkontrolle", "user", "Endkontrolle durchführen und Prüfprotokoll erfassen", 1, 18)
    n("GW07_Qualitaet", "xor", "Qualität in Ordnung?", 1, 19)
    n("GW07_Grenze", "xor", "Zweite Nacharbeit erfolglos?", 1, 20, 1, label="left")
    n("T07_Abbruch", "service", "Auftragsstatus auf 'abgelehnt' setzen", 1, 21, 1)
    n("T07_Nacharbeit", "manual", "Nacharbeit durchführen", 1, 20, 2)
    n("T07_Fertig", "service", "Auftragsstatus auf 'fertig' setzen", 1, 21)
    n("Merge_07z", "xor", "", 1, 22)
    n("End_07", "end", "Reparatur abgeschlossen", 1, 23)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K07_Start", "start", "Nachtrags-KVA erhalten", 11, trigger="message")
    k("K07_Pruefen", "user", "Nachtrag in der App prüfen", 12)
    k("K07_Senden", "send", "Freigabe oder Ablehnung senden", 13)
    k("K07_End", "end", "Nachtrag entschieden", 14)
    f("K07_Start", "K07_Pruefen"); f("K07_Pruefen", "K07_Senden"); f("K07_Senden", "K07_End")
    f("Start_07", "T07_Status"); f("T07_Status", "Merge_07e"); f("Merge_07e", "T07_Entnahme"); f("T07_Entnahme", "Merge_07")
    f("Merge_07", "T07_Start"); f("T07_Start", "T07_Ausfuehren"); f("T07_Ausfuehren", "T07_Doku")
    f("T07_Doku", "GW07_Weitere")
    f("GW07_Weitere", "Merge_07", "ja", "=weitereSchritte", loop=1)
    f("GW07_Weitere", "GW07_Zusatz", "nein", "=not(weitereSchritte)")
    f("GW07_Zusatz", "Join_07", "nein", "=not(zusatzbefund)")
    f("GW07_Zusatz", "T07_Nachtrag", "ja", "=zusatzbefund")
    f("T07_Nachtrag", "T07_NachtragSenden"); f("T07_NachtragSenden", "GW07_Warten")
    f("GW07_Warten", "E07_Entscheidung"); f("GW07_Warten", "E07_Timer")
    f("E07_Entscheidung", "GW07_Nachtrag"); f("E07_Timer", "Merge_07n")
    f("GW07_Nachtrag", "T07_Teile", "ja", "=nachtragFreigegeben")
    f("GW07_Nachtrag", "Merge_07n", "nein", "=not(nachtragFreigegeben)")
    f("T07_Teile", "Merge_07e", via="over")
    f("Merge_07n", "T07_Abgelehnt"); f("T07_Abgelehnt", "Join_07")
    f("Join_07", "T07_Endkontrolle"); f("T07_Endkontrolle", "GW07_Qualitaet")
    f("GW07_Qualitaet", "T07_Fertig", "ja", "=qualitaetOk")
    f("GW07_Qualitaet", "GW07_Grenze", "nein", "=not(qualitaetOk)")
    f("GW07_Grenze", "T07_Nacharbeit", "nein", "=nacharbeiten < 2")
    f("GW07_Grenze", "T07_Abbruch", "ja", "=nacharbeiten >= 2")
    f("T07_Nacharbeit", "Join_07", loop=1)
    f("T07_Fertig", "Merge_07z"); f("T07_Abbruch", "Merge_07z"); f("Merge_07z", "End_07")
    d.msg("T07_NachtragSenden", "K07_Start", "Nachtrags-KVA")
    d.msg("K07_Senden", "E07_Entscheidung", "Freigabe / Ablehnung")
    d.data("T07_Status", "Reparatur-auftrag [in Reparatur]")
    d.data("T07_Entnahme", "Ersatzteil-Reservierung [entnommen]")
    d.data("T07_Doku", "Arbeitszeit-buchung")
    d.data("T07_Nachtrag", "Kosten-voranschlag [Entwurf]", pos="bottom")
    d.data("T07_Abgelehnt", "Kosten-voranschlag [abgelehnt]", pos="bottom")
    d.data("T07_Fertig", "Reparatur-auftrag [fertig]")
    d.data("T07_Abbruch", "Reparatur-auftrag [abgelehnt]", pos="bottom")
    d.store("T07_Status")
    return d


def build_08():
    d = Diagram("08", "Abholung, Rechnung und Zahlung", [SERVICE, TECH], pools_top=[KUNDE],
                doc="Sobald ein Geraet abholbereit ist (repariert, abgelehnt oder nach Nacharbeit), erstellt RepairFlow die Rechnung "
                    "aus KVA und Arbeitszeiten bzw. ueber die Diagnosepauschale (kostenfreie Nacharbeit ohne Rechnung) und "
                    "benachrichtigt den Kunden; nach der dritten Erinnerung wird eine Lagergebuehr berechnet, bleibt auch die vierte "
                    "ohne Abholung, wird die Verwertung des Geraets eingeleitet. Bei der Abholung "
                    "wird die Zahlung erfasst (bar/Karte sofort, auf Rechnung mit Zahlungsziel, bis zu drei Mahnungen, danach "
                    "Inkasso), das Geraet uebergeben "
                    "und der Auftrag geschlossen.")
    n, f = d.node, d.flow
    n("Start_08", "start", "Gerät abholbereit", 0, 0)
    n("GW08_Abr", "xor", "Abrechnung?", 0, 1, label="left")
    n("T08_Rechnung", "service", "Rechnung aus KVA und Arbeitszeiten erstellen", 0, 2, 1)
    n("T08_Pauschale", "service", "Rechnung über Diagnosepauschale erstellen", 0, 2, 2)
    n("Merge_08", "xor", "", 0, 3)
    n("T08_Benachrichtigung", "send", "Abhol-Benachrichtigung an Kunde senden", 0, 5)
    n("GW08_Warten", "event", "", 0, 6)
    n("E08_Timer", "catch", "14 Tage nicht abgeholt", 0, 6, 1, trigger="timer", duration="P14D")
    n("T08_Erinnerung", "service", "Erinnerung protokollieren", 0, 5, 1)
    n("GW08_Dritte", "xor", "Anzahl Erinnerungen?", 0, 5, 2, label="left")
    n("T08_Lager", "service", "Lagergebühr in Rechnung aufnehmen", 0, 5, 3)
    n("T08_Verwertung", "user", "Verwertung des Geräts einleiten", 0, 6, 2)
    n("E08_Kunde", "catch", "Kunde zur Abholung erschienen", 0, 7, trigger="message", msg="Kunde erschienen")
    n("T08_Holen", "manual", "Gerät aus dem Lager holen", 1, 8)
    n("GW08_Faellig", "xor", "Zahlung fällig?", 1, 9)
    n("T08_Zahlungsart", "user", "Zahlungsart erfassen", 0, 10)
    n("GW08_Zahlungsart", "xor", "Zahlungsart?", 0, 11)
    n("T08_Kassieren", "user", "Zahlung kassieren", 0, 12)
    n("T08_Versand", "send", "Rechnung mit Zahlungsziel versenden", 0, 13, 1)
    n("Join_08a", "xor", "", 1, 14)
    n("T08_Uebergabe", "manual", "Reparatur erläutern und Gerät übergeben", 1, 15)
    n("T08_Abgeholt", "service", "Auftrag auf 'abgeholt' setzen und schließen", 0, 16)
    n("T08_Bestaende", "service", "Reservierungen und Bestände abschließen", 0, 17)
    n("GW08_Offen", "xor", "Zahlung?", 0, 18, label="left")
    n("Merge_08z", "xor", "", 0, 19)
    n("GW08_WartenZ", "event", "", 0, 20)
    n("E08_Zahlung", "catch", "Zahlung eingegangen", 0, 21, trigger="message", msg="Zahlungseingang")
    n("E08_TimerZ", "catch", "14 Tage verstrichen", 0, 21, 1, trigger="timer", duration="P14D")
    n("GW08_Mahnstufe", "xor", "Dritte Mahnung erfolglos?", 0, 22, 1)
    n("T08_Mahnung", "send", "Mahnung senden", 0, 23, 1)
    n("T08_Inkasso", "user", "Forderung an Inkasso übergeben", 0, 22, 4)
    n("Merge_08v", "xor", "", 0, 24, 2)
    n("T08_Verbuchen", "service", "Zahlung verbuchen", 0, 25)
    n("Merge_08w", "xor", "", 0, 26, 3)
    n("T08_Bewertung", "send", "Bewertungsanfrage an Kunde senden", 0, 27)
    n("Merge_08e", "xor", "", 0, 28, 4)
    n("Merge_08f", "xor", "", 0, 28)
    n("End_08", "end", "Auftrag abgeschlossen", 0, 29)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K08_Start", "start", "Abholbenachrichtigung erhalten", 5, trigger="message")
    k("K08_Weg", "manual", "Zur Filiale kommen", 6)
    k("K08_Abholen", "send", "Abholung in der Filiale anmelden", 7)
    k("K08_GW1", "xor", "Zahlung fällig?", 9)
    k("K08_Art", "send", "Zahlungsart mitteilen", 10)
    k("K08_GW", "xor", "Zahlungsart?", 11)
    k("K08_Bar", "send", "Bar oder mit Karte bezahlen", 12)
    k("K08_Rechnung", "catch", "Rechnung erhalten", 13, 1, trigger="message")
    k("K08_Join1", "xor", "", 14, 2)
    k("K08_Geraet", "catch", "Gerät erhalten", 15, trigger="message")
    k("K08_GW2", "xor", "Rechnung offen?", 16)
    k("K08_Ueberweisen", "send", "Rechnungsbetrag überweisen", 17, 1)
    k("K08_Join2", "xor", "", 18)
    k("K08_Bewertung", "catch", "Bewertungsanfrage erhalten", 27, trigger="message")
    k("K08_End", "end", "Gerät abgeholt", 29)
    f("K08_Start", "K08_Weg"); f("K08_Weg", "K08_Abholen"); f("K08_Abholen", "K08_GW1")
    f("K08_GW1", "K08_Art", "ja", "=zahlungFaellig")
    f("K08_GW1", "K08_Join1", "nein", "=not(zahlungFaellig)")
    f("K08_Art", "K08_GW")
    f("K08_GW", "K08_Bar", "bar / Karte", '=zahlungsart in ["bar", "karte"]')
    f("K08_GW", "K08_Rechnung", "auf Rechnung", '=zahlungsart = "rechnung"')
    f("K08_Bar", "K08_Join1"); f("K08_Rechnung", "K08_Join1"); f("K08_Join1", "K08_Geraet", via="right"); f("K08_Geraet", "K08_GW2")
    f("K08_GW2", "K08_Ueberweisen", "ja", "=rechnungOffen")
    f("K08_GW2", "K08_Join2", "nein", "=not(rechnungOffen)")
    f("K08_Ueberweisen", "K08_Join2"); f("K08_Join2", "K08_Bewertung"); f("K08_Bewertung", "K08_End")
    f("Start_08", "GW08_Abr")
    f("GW08_Abr", "T08_Rechnung", "Reparatur", '=abrechnung = "reparatur"')
    f("GW08_Abr", "T08_Pauschale", "Diagnosepauschale", '=abrechnung = "pauschale"')
    f("GW08_Abr", "Merge_08", "kostenfrei", '=abrechnung = "kostenfrei"')
    f("T08_Rechnung", "Merge_08"); f("T08_Pauschale", "Merge_08")
    f("Merge_08", "T08_Benachrichtigung"); f("T08_Benachrichtigung", "GW08_Warten")
    f("GW08_Warten", "E08_Kunde"); f("GW08_Warten", "E08_Timer")
    f("E08_Timer", "T08_Erinnerung"); f("T08_Erinnerung", "GW08_Dritte")
    f("GW08_Dritte", "Merge_08", "< 3", "=erinnerungen < 3")
    f("GW08_Dritte", "T08_Lager", "= 3", "=erinnerungen = 3")
    f("GW08_Dritte", "T08_Verwertung", "> 3", "=erinnerungen > 3")
    f("T08_Lager", "Merge_08"); f("T08_Verwertung", "Merge_08e", loop=3)
    f("E08_Kunde", "T08_Holen"); f("T08_Holen", "GW08_Faellig")
    f("GW08_Faellig", "T08_Zahlungsart", "ja", "=rechnungVorhanden")
    f("GW08_Faellig", "Join_08a", "nein", "=not(rechnungVorhanden)")
    f("T08_Zahlungsart", "GW08_Zahlungsart")
    f("GW08_Zahlungsart", "T08_Kassieren", "bar / Karte", '=zahlungsart in ["bar", "karte"]')
    f("GW08_Zahlungsart", "T08_Versand", "auf Rechnung", '=zahlungsart = "rechnung"')
    f("T08_Kassieren", "Join_08a"); f("T08_Versand", "Join_08a"); f("Join_08a", "T08_Uebergabe")
    f("T08_Uebergabe", "T08_Abgeholt"); f("T08_Abgeholt", "T08_Bestaende"); f("T08_Bestaende", "GW08_Offen")
    f("GW08_Offen", "Merge_08z", "auf Rechnung", '=zahlungsart = "rechnung"')
    f("GW08_Offen", "Merge_08v", "bar / Karte kassiert", '=zahlungsart in ["bar", "karte"]')
    f("GW08_Offen", "Merge_08w", "keine Rechnung", '=abrechnung = "kostenfrei"')
    f("Merge_08z", "GW08_WartenZ"); f("GW08_WartenZ", "E08_Zahlung"); f("GW08_WartenZ", "E08_TimerZ")
    f("E08_TimerZ", "GW08_Mahnstufe")
    f("GW08_Mahnstufe", "T08_Mahnung", "nein", "=mahnungen < 3")
    f("GW08_Mahnstufe", "T08_Inkasso", "ja", "=mahnungen >= 3")
    f("T08_Mahnung", "Merge_08z", loop=1); f("T08_Inkasso", "Merge_08e")
    f("E08_Zahlung", "Merge_08v"); f("Merge_08v", "T08_Verbuchen", via="right"); f("T08_Verbuchen", "Merge_08w")
    f("Merge_08w", "T08_Bewertung", via="right"); f("T08_Bewertung", "Merge_08f"); f("Merge_08e", "Merge_08f"); f("Merge_08f", "End_08")
    d.msg("T08_Benachrichtigung", "K08_Start", "Abhol-Benachrichtigung (ggf. Erinnerung)")
    d.msg("K08_Abholen", "E08_Kunde", "Abholung")
    d.msg("K08_Art", "T08_Zahlungsart", "Zahlungsart")
    d.msg("K08_Bar", "T08_Kassieren", "Barzahlung / Kartenzahlung")
    d.msg("T08_Versand", "K08_Rechnung", "Rechnung")
    d.msg("T08_Uebergabe", "K08_Geraet", "Gerät + Erläuterung")
    d.msg("K08_Ueberweisen", "E08_Zahlung", "Zahlung")
    d.msg("T08_Mahnung", KUNDE, "Mahnung")
    d.msg("T08_Bewertung", "K08_Bewertung", "Bitte um Bewertung")
    d.data("T08_Rechnung", "Rechnung [offen]", pos="top")
    d.data("T08_Pauschale", "Rechnung [offen]", pos="bottom")
    d.data("T08_Abgeholt", "Reparatur-auftrag [abgeholt]")
    d.data("T08_Mahnung", "Rechnung [Mahnung]", pos="top")
    d.data("T08_Verbuchen", "Rechnung [bezahlt]")
    d.store("T08_Verbuchen", name="Buchhaltung (DATEV-Export)")
    d.store("T08_Abgeholt")
    return d


def build_09():
    d = Diagram("09", "Reklamation und Gewährleistung", [TECH, SERVICE, LEITUNG], pools_top=[KUNDE], shift=2,
                doc="Meldet der Kunde nach der Abholung einen Mangel, wird die Reklamation dem Ursprungsauftrag zugeordnet, "
                    "der Mangel geprueft und der Gewaehrleistungsfall bewertet. Je nach Ergebnis folgt kostenfreie Nacharbeit "
                    "(Freigabe durch die Werkstattleitung) oder ein kostenpflichtiges Angebot. Die Nacharbeit wird als neuer "
                    "Reparaturauftrag angelegt und ueber Prozess 07 durchgefuehrt; die Rueckgabe des Geraets laeuft in jedem "
                    "Fall ueber Prozess 08.")
    n, f = d.node, d.flow
    n("Start_09", "start", "Mangel gemeldet", 1, 0, trigger="message", msg="Reklamation")
    n("T09_Erfassen", "user", "Reklamation erfassen", 1, 1)
    n("T09_Zuordnen", "service", "Ursprungsauftrag und Rechnung zuordnen", 1, 2)
    n("T09_Annehmen", "user", "Gerät annehmen und Mangel dokumentieren", 1, 3)
    n("T09_Pruefen", "manual", "Mangel prüfen", 0, 4)
    n("T09_Bewerten", "businessRule", "Gewährleistungsfall bewerten", 0, 5, type="repairflow.gewaehrleistung")
    n("GW09_Gewaehr", "xor", "Gewährleistung?", 0, 6, label="left")
    n("T09_Freigeben", "user", "Kostenfreie Nacharbeit freigeben", 2, 7)
    n("T09_Angebot", "send", "Kostenpflichtiges Angebot senden", 1, 7)
    n("T09_Entscheidung", "receive", "Kundenentscheidung empfangen", 1, 8, msg="Angebotsentscheidung")
    n("GW09_Angebot", "xor", "Angebot angenommen?", 1, 9, label="left")
    n("T09_Abgelehnt", "service", "Reklamation als abgelehnt markieren", 1, 11, 1)
    n("Join_09a", "xor", "", 0, 10)
    n("T09_Auftrag", "service", "Nacharbeitsauftrag anlegen", 0, 11)
    n("T09_Info", "send", "Kunde über Nacharbeit informieren", 1, 12)
    n("T09_Reparatur", "call", "07 Reparatur durchführen", 0, 13, called="Proc_07")
    n("GW09_Teil", "xor", "Lieferantenteil defekt?", 0, 14)
    n("T09_Retoure", "call", "10 Retoure abwickeln", 0, 15, 1, called="Proc_10")
    n("Join_09b", "xor", "", 0, 16)
    n("T09_Abholung", "call", "08 Abholung abwickeln", 0, 17, called="Proc_08")
    n("T09_Abschluss", "service", "Reklamation abschließen", 1, 18)
    n("End_09", "end", "Reklamation abgeschlossen", 1, 19)
    d.partner(KUNDE)
    k = lambda *a, **kw: d.pnode(KUNDE, *a, **kw)
    k("K09_Start", "start", "Mangel festgestellt", 0)
    k("K09_Melden", "send", "Mangel in der App melden", 2)
    k("K09_Bringen", "manual", "Gerät in die Filiale bringen", 3)
    k("K09_Abgeben", "send", "Gerät abgeben", 4)
    k("K09_Merge", "xor", "", 6)
    k("K09_Warten", "event", "", 7)
    k("K09_Angebot", "catch", "Angebot erhalten", 9, 1, trigger="message")
    k("K09_Entscheiden", "send", "Angebot annehmen oder ablehnen", 10, 1)
    k("K09_GW", "xor", "Angebot angenommen?", 11, 1)
    k("K09_Info", "catch", "Nacharbeit angekündigt", 12, trigger="message")
    k("K09_Join", "xor", "", 18, 1)
    k("K09_End", "end", "Reklamation erledigt", 19, 1)
    f("K09_Start", "K09_Melden"); f("K09_Melden", "K09_Bringen"); f("K09_Bringen", "K09_Abgeben"); f("K09_Abgeben", "K09_Merge")
    f("K09_Merge", "K09_Warten")
    f("K09_Warten", "K09_Angebot"); f("K09_Warten", "K09_Info")
    f("K09_Angebot", "K09_Entscheiden"); f("K09_Entscheiden", "K09_GW")
    f("K09_GW", "K09_Merge", "ja", "=angebotAngenommen", loop=1)
    f("K09_GW", "K09_Join", "nein", "=not(angebotAngenommen)")
    f("K09_Info", "K09_Join"); f("K09_Join", "K09_End")
    f("Start_09", "T09_Erfassen"); f("T09_Erfassen", "T09_Zuordnen"); f("T09_Zuordnen", "T09_Annehmen")
    f("T09_Annehmen", "T09_Pruefen"); f("T09_Pruefen", "T09_Bewerten"); f("T09_Bewerten", "GW09_Gewaehr")
    f("GW09_Gewaehr", "T09_Freigeben", "ja", "=gewaehrleistung")
    f("GW09_Gewaehr", "T09_Angebot", "nein", "=not(gewaehrleistung)", via="right")
    f("T09_Angebot", "T09_Entscheidung"); f("T09_Entscheidung", "GW09_Angebot")
    f("GW09_Angebot", "Join_09a", "ja", "=angebotAngenommen")
    f("GW09_Angebot", "T09_Abgelehnt", "nein", "=not(angebotAngenommen)", via="right")
    f("T09_Freigeben", "Join_09a"); f("Join_09a", "T09_Auftrag"); f("T09_Auftrag", "T09_Info"); f("T09_Info", "T09_Reparatur")
    f("T09_Reparatur", "GW09_Teil")
    f("GW09_Teil", "T09_Retoure", "ja", "=lieferantenteilDefekt")
    f("GW09_Teil", "Join_09b", "nein", "=not(lieferantenteilDefekt)")
    f("T09_Retoure", "Join_09b"); f("T09_Abgelehnt", "Join_09b"); f("Join_09b", "T09_Abholung")
    f("T09_Abholung", "T09_Abschluss"); f("T09_Abschluss", "End_09")
    d.msg("K09_Melden", "Start_09", "Mangelmeldung")
    d.msg("K09_Abgeben", "T09_Annehmen", "Gerät")
    d.msg("T09_Angebot", "K09_Angebot", "Angebot", snap=False)
    d.msg("K09_Entscheiden", "T09_Entscheidung", "Annahme / Ablehnung")
    d.msg("T09_Info", "K09_Info", "Info: Nacharbeit (kostenfrei / zum Angebot)")
    d.data("T09_Erfassen", "Reklamation")
    d.data("T09_Zuordnen", "Reparatur-auftrag [abgeholt]", dir="in")
    d.data("T09_Bewerten", "Fehlerbefund", dir="in")
    d.data("T09_Auftrag", "Reparatur-auftrag [angenommen]")
    d.store("T09_Abschluss")
    return d


def build_10():
    d = Diagram("10", "Ersatzteil-Retoure und Lieferanten-Reklamation", [LEITUNG, DISPO], pools_bottom=[LIEF],
                doc="Defekte oder falsche Lieferantenteile werden beim Lieferanten reklamiert. Nach RMA-Freigabe wird das Teil "
                    "zurueckgesendet, der Bestand korrigiert und je nach Rueckmeldung Ersatzlieferung oder Gutschrift verbucht. "
                    "Antwortet der Lieferant auch nach der zweiten Eskalation nicht, wird das Teil abgeschrieben. Ob nach einer "
                    "Gutschrift neu bestellt wird, entscheidet der aufrufende Prozess 06.")
    n, f = d.node, d.flow
    n("Start_10", "start", "Mangelhaftes Teil festgestellt", 1, 0)
    n("T10_Grund", "user", "Retourengrund erfassen", 1, 1)
    n("T10_Ermitteln", "service", "Bestellposition und Lieferanten ermitteln", 1, 2)
    n("T10_Anmelden", "send", "Retoure beim Lieferanten anmelden", 1, 3)
    n("Merge_10", "xor", "", 1, 4)
    n("GW10_Warten", "event", "", 1, 5)
    n("E10_Timer", "catch", "5 Tage verstrichen", 1, 6, trigger="timer", duration="P5D")
    n("E10_RMA", "catch", "RMA-Freigabe erhalten", 1, 6, 1, trigger="message", msg="RMA-Freigabe", label="above")
    n("GW10_Zweite", "xor", "Bereits eskaliert?", 0, 6, 1)
    n("T10_Eskalieren", "send", "Eskalation an Lieferanten senden", 0, 7)
    n("T10_Abschreiben", "service", "Teil abschreiben", 0, 8, 1)
    n("T10_Versenden", "manual", "Teil verpacken und versenden", 1, 8)
    n("T10_Bestand", "service", "Lagerbestand korrigieren", 1, 9)
    n("T10_Rueckmeldung", "receive", "Rückmeldung des Lieferanten empfangen", 1, 10, msg="Retourenrückmeldung")
    n("GW10_Art", "xor", "Ersatz oder Gutschrift?", 1, 11)
    n("T10_Ersatz", "user", "Ersatzlieferung buchen", 1, 12)
    n("T10_Gutschrift", "service", "Gutschrift verbuchen", 1, 12, 1)
    n("Join_10a", "xor", "", 1, 13)
    n("T10_Abschluss", "service", "Retoure dokumentieren und abschließen", 1, 14)
    n("End_10", "end", "Retoure abgeschlossen", 1, 15)
    f("Start_10", "T10_Grund"); f("T10_Grund", "T10_Ermitteln"); f("T10_Ermitteln", "T10_Anmelden")
    f("T10_Anmelden", "Merge_10"); f("Merge_10", "GW10_Warten")
    f("GW10_Warten", "E10_Timer"); f("GW10_Warten", "E10_RMA")
    f("E10_Timer", "GW10_Zweite")
    f("GW10_Zweite", "T10_Eskalieren", "nein", "=not(eskaliert)")
    f("GW10_Zweite", "T10_Abschreiben", "ja", "=eskaliert")
    f("T10_Eskalieren", "Merge_10", via="over")
    f("T10_Abschreiben", "Join_10a")
    f("E10_RMA", "T10_Versenden"); f("T10_Versenden", "T10_Bestand"); f("T10_Bestand", "T10_Rueckmeldung")
    f("T10_Rueckmeldung", "GW10_Art")
    f("GW10_Art", "T10_Ersatz", "Ersatz", '=rueckmeldung = "ersatz"')
    f("GW10_Art", "T10_Gutschrift", "Gutschrift", '=rueckmeldung = "gutschrift"')
    f("T10_Ersatz", "Join_10a"); f("T10_Gutschrift", "Join_10a"); f("Join_10a", "T10_Abschluss"); f("T10_Abschluss", "End_10")
    d.msg("T10_Anmelden", LIEF, "Retoure anmelden")
    d.msg(LIEF, "E10_RMA", "RMA-Nummer")
    d.msg("T10_Eskalieren", LIEF, "Eskalation")
    d.msg("T10_Versenden", LIEF, "Rücksendung")
    d.msg(LIEF, "T10_Rueckmeldung", "Ersatz / Gutschrift")
    d.data("T10_Ermitteln", "Lieferanten-bestellung", dir="in")
    d.data("T10_Anmelden", "Lieferanten-bestellung [Retoure]")
    d.data("T10_Bestand", "Lagerbestand")
    d.data("T10_Gutschrift", "Lieferanten-bestellung [Gutschrift]", pos="bottom")
    d.store("T10_Abschluss")
    return d


DIAGRAMS = [build_01(), build_02(), build_03(), build_04(), build_05(), build_06(), build_07(), build_08(), build_09(), build_10()]

SLUGS = {"01": "Sofortdiagnose", "02": "Auftragsannahme", "03": "Fehlerdiagnose", "04": "Kostenvoranschlag",
         "05": "Ersatzteilreservierung", "06": "Ersatzteilbestellung", "07": "Reparaturdurchfuehrung",
         "08": "Abholung", "09": "Reklamation", "10": "Retoure"}

if __name__ == "__main__":
    import os, sys
    out = sys.argv[1] if len(sys.argv) > 1 else "out"
    os.makedirs(out, exist_ok=True)
    total = 0
    for d in DIAGRAMS:
        xml = d.to_xml()
        fn = os.path.join(out, "p%s-%s.bpmn" % (d.num, SLUGS[d.num].lower()))
        with open(fn, "w", encoding="utf-8") as fh:
            fh.write(xml)
        c = d.activity_count()
        total += c
        ck = sum(d.activity_count(p) for p in d.partners)
        print("%s  activities=%2d (+%d Kunde)  pool=%dx%d  %s" % (fn, c, ck, d.pool_w, d.pool_h, d.name))
    print("average activities: %.1f" % (total / len(DIAGRAMS)))
